### ISSUE TITLE
Multiple includes with filters enabled cause field mismatches.

### ISSUE THREAD

**Issue by Relic79** [jcachat/EntityFramework.DynamicFilters#10]
I don't know how to explain this, but essentially if I run a query and include multiple navigation entities, and on some of those, I include other child entities, the query becomes quite complex, and I started seeing properties being returned with values that weren't correct. When I compared the query generated with the filters to the one without and ran them against my database, I found the column that contained the proper data in the unfiltered query ,and it was different then the same column after.

I will likely need to make you a reproduction, but in the dynamic filtered query the columns I found incorrect are:

`Join7`.`CropID` AS `CropID2`, 
`Join7`.`Name` AS `Name5`, 
`Join7`.`Abbreviation` AS `Abbreviation2`, 
`Join7`.`CompanyID` AS `CompanyID4`, 
`Join7`.`Active` AS `Active8`, 
`Join7`.`Created` AS `Created8`, 
`Join7`.`CreatedBy` AS `CreatedBy7`, 
`Join7`.`Edited` AS `Edited8`, 
`Join7`.`EditedBy` AS `EditedBy7`, 

When I run the same with Dynamic Filters removed, those columns are:
`Join7`.`CROPID2` AS `CropID2`, 
`Join7`.`NAME2` AS `Name5`, 
`Join7`.`ABBREVIATION2` AS `Abbreviation2`, 
`Join7`.`COMPANYID2` AS `CompanyID4`, 
`Join7`.`ACTIVE4` AS `Active8`, 
`Join7`.`CREATED4` AS `Created8`, 
`Join7`.`CREATEDBY3` AS `CreatedBy7`, 
`Join7`.`EDITED4` AS `Edited8`, 
`Join7`.`EDITEDBY3` AS `EditedBy7`, 

Without the repro, I can tell you that My entities have properties like "PreviousCrop" and "CurrentCrop" that both point to a Crop Type, or in this case I have entities like so:

Contract:
ID
Name

ContractToCropYear:
ID
ContractID
CropYearID

CropYear:
ID
PreviousCrop
CurrentCrop
CurrentVariety

Crop:
ID
Name

Variety:
ID
Name
CropID
OtherInfo

Essentially when I ask the context for a contract including all ContractToCropYears, Including all CropYears, Including the PreviousCrop, CurrentCrop, and Variety, the filtered queries generated (on MySQL) don't seem to track and match the correct projections.

I hope that made sense and that the explanation and examples can point you to where the issue might be. I am sure it has something to do with the 2 types of the different properties being the same, and so it matches to the wrong query.

Thanks you've been super helpful and responsive! I am still trying to find time to fix that interface issue I logged as I'd love to contribute rather then just find bugs!

Steve

**Comment by jcachat** [comment]
This may be the same issue as #17.  I just checked in a fix for that.  Could you re-test with that fix and see if your situation has been corrected too?
