### ISSUE TITLE
Many to Many filtering

### ISSUE THREAD

**Issue by jrsanbornjr** [jcachat/EntityFramework.DynamicFilters#103]
Hi,
Sorry if this is the wrong to place for this question. It's the only place I could find to contact. Great code here and it was a real godsend for me. I have an unusual schema I created where all the records in various tables have a "version" field. It lets me add a "version" filter and my application shows all relevant data up to a selected version. Everything is working perfectly up to the m2m relationships. My m2m table has a third column with the version and it doesn't get filtered in select queries. I realize a 3rd column in the m2m table is non standard so not something you're likely to address in this app, so I'm hoping you could point me to some documentation or a sample of your code here where I might discern a way to append that additional column filter to the join table in the EF select queries. Many thanks.

**Comment by jcachat** [comment]
I would need to see the relevant models and filters to be sure, but it sounds like there is no filter defined on your many-to-many table.  

Those non-standard m2m relationship entities/tables should still get filtered just like any other entity.

**Comment by jrsanbornjr** [comment]
Hi, and thanks for the reply. Let's take a simple schema example:

Person:
 Id int,
 FirstName varchar,
 LastName varchar,
 Version int

Person_Widget:
 Person.Id,
 Widget.Id,
 Version

Widget
 Id int,
 ItemName varchar,
 ItemDescription varchar,
 Version int


So in this example, Id AND Version make primary keys, so the Version is
required in the join table distinguish the correct records to pair.
Version, however, is only in the database and not part of object model key,
since the filtering ensures a consistent data set is returned. The join
table is in the mapping but not an entity on its own, since EF doesn't
really deal with extra fields in a m2m join table (unless it's defined as a
separate entity with one to many relationships on either side.) I have the
updates and deletes and everything else in this application handled and
working fine, the one detail I haven't got figured out is how to insert a
filter for Version on the join table in m2m queries. I can only imagine
that would be possible via some method in an interceptor. Make sense?

**Comment by jcachat** [comment]
The m2m does exist as an entity inside EF - whether you specifically create it or not.  EF infers it and creates it inside it's metadata (which is then used to create the actual database table).  The only way a filter can be applied to it, is to create a filter on it.  So from what you described, you have not manually created that entity (and rely on EF to do that for you) therefore you have not created a filter on it.

The only solution will be for you to manually create that m2m entity and then create a filter on it.  You can do that for a m2m relationship.  I have done this myself in my own project and it works.

**Comment by jrsanbornjr** [comment]
OK, I added an entity to match the table name of the join table. It
implements the interface that triggers the filter, but it isn't filtering
that join table. The mapping is configured in the PersonMap class like so:

           HasMany(t => t.Widgets)
                .WithMany(t => t.Persons)
                .Map(m =>
                    {
                        m.ToTable("Person_Widget")
                         .MapLeftKey("Person.Id")
                         .MapRightKey("Widget.Id");
                    });

I added an entity for Person_Widget but the filter doesn't seem to be
picking it up. Would it be necessary to create two one to many
relationships on either side of this join entity rather than just defining
the m2m relationship? If that is case, I'd rather figure out, if possible,
how to append that clause to the join clause that EF creates on the join
table.

**Comment by jcachat** [comment]
Did you create a "PersonWidget" class that implements your interface (that has the filter defined on it)?  The mapping you are showing does not indicate that.  Posting some code would help - I'm am just continually guessing at what you are doing...

**Comment by jrsanbornjr** [comment]
Person:
 Id int,
 FirstName varchar,
 LastName varchar,
 Version int

Person_Widget:
 Person.Id,
 Widget.Id,
 Version

Widget
 Id int,
 ItemName varchar,
 ItemDescription varchar,
 Version int


This is the table schema.




           HasMany(t => t.Widgets)
                .WithMany(t => t.Persons)
                .Map(m =>
                    {
                        m.ToTable("Person_Widget")
                         .MapLeftKey("Person.Id")
                         .MapRightKey("Widget.Id");
                    });

This is how they are mapped.


With this mapping, EF creates dynamically a PersonWidget entity for the
relationship. I tried making a PersonWidget class to filter on, but EF
responded by creating a PersonWidget1 entity of it's own. It seems the only
way to make this work is to map one-to-many relationships from Person and
Widget to PersonWidget and treat it as three separate entities with two
one-to-many foreign key relationships on either side of the join table. I
would prefer to leave the many-to-many mapping and find a way to code the
filter into an interceptor class.


The current mapping creates SQL output that looks something like this:

(SELECT
    [Extent1].[Id] AS [PersonId],
    [Extent1].[FirstName] AS [FirstName],
    [Extent1].[LastName] AS [LastName],
    [Extent1].[Version] AS [Version]
    FROM [dbo].[Person] AS [Extent1]
    WHERE [Extent1].[Version] = @DynamicFilterParam_000001) AS [Limit1]
    LEFT OUTER JOIN (SELECT
        [Extent2].[PersonId] AS [PersonId],
        [Extent3].[Id] AS [WidgetId],
        [Extent3].[ItemName],
        [Extent3].[ItemDescription],
        [Extent3].[Version]
        FROM [dbo].[PersonWidget] AS [Extent2]
        INNER JOIN [dbo].[Widget] AS [Extent3]
        ON [Extent2].[WidgetId] = [Extent3].[WidgetId]) AS [Join1]
        ON [Limit1].[PersonId] = [Join1].[PersonId]
        AND [Join1].[Version] = @DynamicFilterParam_000001


I would like to be able to generate SQL like this:

(SELECT
    [Extent1].[Id] AS [PersonId],
    [Extent1].[FirstName] AS [FirstName],
    [Extent1].[LastName] AS [LastName],
    [Extent1].[Version] AS [Version]
    FROM [dbo].[Person] AS [Extent1]
    WHERE [Extent1].[Version] = @DynamicFilterParam_000001) AS [Limit1]
    LEFT OUTER JOIN (SELECT
        [Extent2].[PersonId] AS [PersonId],
        [Extent3].[Id] AS [WidgetId],
        [Extent3].[ItemName],
        [Extent3].[ItemDescription],
        [Extent3].[Version]
        FROM [dbo].[PersonWidget] AS [Extent2]
        INNER JOIN [dbo].[Widget] AS [Extent3]
        ON [Extent2].[WidgetId] = [Extent3].[WidgetId]
        AND [Extent2].[Version] = @DynamicFilterParam_000001) AS [Join1]
        ON [Limit1].[PersonId] = [Join1].[PersonId]
        AND [Join1].[Version] = @DynamicFilterParam_000001


or something equivalent. I just need to get the filter applied to the join
table. Make sense?

**Comment by jrsanbornjr** [comment]
PS

I also posted a question here
http://stackoverflow.com/questions/43795619/entity-framework-6-many-to-many-with-additional-field
with a couple example links, if it helps any. It seems to be a fairly
common request, but not a good answer yet.

**Comment by jcachat** [comment]
Adding the mapping like you did is *NOT* what I am recommending.  You need to follow the answer in the very first link you included in your StackOverflow question (http://stackoverflow.com/questions/42691857/entity-framework-many-to-many-with-additional-column/42692139#42692139) to create the c# class as the m2m join between your Person and Widget tables (i.e. a c# class named PersonWidget).

Once you have done that, you can attache a filter to that PersonWidget class (or make it implement an interface if that's how your existing filter is defined).  A filter *CANNOT* be attached to a relationship that EF infers (creates dynamically).  It can only be attached to a c# class that you create.  There is no other way it can be done.  Hopefully, that is clear now.

I'm not sure what problem you are having creating a c# m2m class.  I have done it exactly as instructed by the answer in that link and it works fine.  Maybe try adding the Table attribute to the top of that class to manually name the table?  And make sure you are not manually specifying the mapping - EF will figure it out on it's own.  Perhaps it came up with PersonWidget1 because you had left your mapping statement in there so it chose PersonWidget1 to avoid a conflict with that mapping.

**Comment by jrsanbornjr** [comment]
Got it. Thank you!
