### ISSUE TITLE
The property 'Id' is part of the object's key information and cannot be modified.

### ISSUE THREAD

**Issue by danhowelldev** [jcachat/EntityFramework.DynamicFilters#108]
I have an EF context that runs seed data on every startup.

Since adding the DynamicFilters library, and adding the following to my context as follows:

`modelBuilder.Filter("IsDeleted", (EntityBase e) => e.IsDeleted, false);`

Where EntityBase is my base entity with an IsDeleted property,

I am getting the following error _intermittently_ on app start - it doesn't seem to happen all the time. 

`The property 'Id' is part of the object's key information and cannot be modified.`

If I comment out the above filter line, build, and run, everything works. I can then uncomment the line again and it works for a little while - usually for a couple of builds and then the issue resurfaces. 

Any ideas what would be causing this issue?

**Comment by jcachat** [comment]
I have no idea where that would be coming from.  That error is related to saving entities to the database which is something that Dynamic Filters is not involved in at all.

Do you have a stack trace that implicates Dynamic Filters?

Are you doing anything async when seeding your database?  Maybe try moving the filter setup before/after seeding (opposite whatever it is now)?  "intermittently" usually smells like a timing/threading/async issue.  The filter setup could be changing the timing somehow, but it's a very quick process and then is not involved at all in saving entities.  Honestly, I don't have enough information to make any other guesses.

**Comment by danhowelldev** [comment]
Thanks for the prompt reply. I'll do some more investigation and see if I can dig a little deeper and let you know what I find.

**Comment by danhowelldev** [comment]
FYI I solved this issue - it was to do with a 1:1 relationship in my data model.

Thanks!

**Comment by jzabroski** [comment]
> I am getting the following error _intermittently_ on app start - it doesn't seem to happen all the time.

@danhowelldev While this is a three year old issue, I am running into a similar issue now.  It seems to happen whenever I use ZZZProjects logic followed by any EF6 logic that invokes the internal ObjectStateManager.  Why, I'm not sure.
