### ISSUE TITLE
Filter by NavigationProperty

### ISSUE THREAD

**Issue by adrianotrentim** [jcachat/EntityFramework.DynamicFilters#11]
Hi John,

I had another idea (need) here. I need a condition for NavigationProperty, must reach a certain field in a parent table is equal "NNNNN" as in the example below:

modelBuilder.Filter(GetType().Name, (Menu query, List<Guid> values) =>
                query.IdTipoMenu == 0 ||
                query.Descricao == "XXX - SETRIN" ||
                <b>query.MenuSuperior.Descricao == "XXX - SETRIN"</b> ||
                values.Contains(query.IdMenu),
                () =>
                {
                    if (FilteredValues().Get<Guid>(GetType().Name) == null)
                    {
                        var modulosDisponiveis = new Repositorio<ModuloDisponivel>().ObjectSet.Where(t => t.Disponivel).Select(t => t.IdModulo).ToList();
                        var modulos = new Repositorio<ModuloItem>().ObjectSet.Where(m => modulosDisponiveis.Contains(m.IdModulo) && m.IdMenu != null).Select(t => (Guid)t.IdMenu).ToList();

                        FilteredValues().Set(GetType().Name, modulos.ToList());
                    }

                    return FilteredValues().Get<Guid>(GetType().Name);
                });

Any ideas to make an Inner Join automatically when the library to identify the property is a NavigationProperty?

**Comment by Ibrahim-Islam** [comment]
Would like to be able to filter with navigation properties also e.g.
```
modelBuilder.Filter("Projects", (Project p) => p.Customer.OrganizationId, 0)
```

**Comment by jcachat** [comment]
I just released v2 with support for filtering on navigation properties as well as a couple other new features.  See https://github.com/jcachat/EntityFramework.DynamicFilters#changes-in-version-2 for change list.
