### ISSUE TITLE
Attempting to create a LINQ filter results in compile error

### ISSUE THREAD

**Issue by tbrettallen** [jcachat/EntityFramework.DynamicFilters#110]
I'm attempting to read the documentation for this and have come up with the following code:

```
1.     modelBuilder.Filter("ChmPeople_ChurchId",
2.                (IChurchDataPrivileged entity, bool enforcePermissions, int churchId) => !enforcePermissions || entity.ChurchId == churchId,
3.                () => ShouldEnforcePermissions,
4.                () => CurrentUser.ChurchId);
```

Each lambda line has it's own error though:
Line 2: Delegate 'Expression<Func<IChurchDataPrivileged, bool, bool>>' does not take 3 arguments.
Line 3: Argument type 'lambda expression' is not assignable to parameter type 'bool'
Line 4: Delegate 'Func<Type,bool>' does not take 0 arguments

ShouldEnforcePermissions and CurrentUser are static properties on the DB Context.

**Comment by jcachat** [comment]
If they are properties in your DbContext, you need to specify that in your parameter definitions like this:
```
modelBuilder.Filter("ChmPeople_ChurchId",
                (IChurchDataPrivileged entity, bool enforcePermissions, int churchId) => !enforcePermissions || entity.ChurchId == churchId,
                (MyDbContext ctx) => ctx.ShouldEnforcePermissions,
                (MyDbContext ctx) => ctx.CurrentUser.ChurchId);
```

As shown here: https://github.com/jcachat/EntityFramework.DynamicFilters#parameter-expressions

**Comment by tbrettallen** [comment]
My mistake! 

This works fine:

```
            modelBuilder.Filter("ChmPeople_ChurchId",
                (IChurchDataPrivileged entity, bool enforcePermissions, int churchId) => !enforcePermissions || entity.ChurchId == churchId,
                () => ShouldEnforcePermissions,
                () => CurrentUser.ChurchId.GetValueOrDefault());
```

Type inference wasn't working due to ChurchId being int? instead of just int!

**Comment by jcachat** [comment]
It will not work correctly if those are non-static properties in your DbContext.  It may compile and seem fine, but it will constantly be referencing the DbContext instance used to define the filters.  You need to use the syntax I just showed if you need those values to come from the current DbContext instance.

**Comment by tbrettallen** [comment]
They are static properties.
