### ISSUE TITLE
EnableFilter(name, condition) works opposite than expected

### ISSUE THREAD

**Issue by tbrettallen** [jcachat/EntityFramework.DynamicFilters#112]
In my testing, when I do have the following:

```
            builder.Filter("ChmActivity_ContactItem",
                (ContactItem contactItem, List<int> allowedIds) => allowedIds.Contains(contactItem.MinistryId),
                () => GetReadableMinistries());

            builder.EnableFilter("ChmActivity_ContactItem", () => false);
```

the filter is applied, and when I use true, the filter is not applied.

According to the documentation, a value of true should enable the filter, not false:

> For example:
> 
```
modelBuilder.Filter("BlogEntryFilter", (BlogEntry b, Guid accountID) => (b.AccountID == accountID), 
                  () => GetPersonIDFromPrincipal(Thread.CurrentPrincipal));
modelBuilder.EnableFilter("BlogEntryFilter", () => !UserIsAdmin(Thread.CurrentPrincipal));
```
> creates a filter on BlogEntry records to restrict to only the current uses AccountID. But the filter will only be enabled if the user is not an Admin user.

**Comment by jcachat** [comment]
I'm not seeing that happening.  Take a look at the unit tests I have in DisableFilterTests.cs for the DisableFilter_GloballyEnableByGenericCondition() method and EntityF.  It's testing that exact scenario and it works as it should - false disables the filter and true enables it.
