### ISSUE TITLE
json filed filter

### ISSUE THREAD

**Issue by mwinner313** [jcachat/EntityFramework.DynamicFilters#116]
i have a json filed like

 `   

  private string AllowedRolesPremissionJsonString { get; set; }

 [NotMapped]
 public ObservableCollection<RolePremission> AllowedRolesPermissions
        {
            get
            {
                var additionalPermissions
                       = JsonConvert.DeserializeObject<ObservableCollection<RolePremission>>
                        (AllowedRolesPremissionJsonString ?? string.Empty) ?? new 
                       ObservableCollection<RolePremission>();
                additionalPermissions.CollectionChanged += SaveToPremissinBackingField;
                return additionalPermissions;
            }
            set { AllowedRolesPremissionJsonString = JsonConvert.SerializeObject(value); }
        }
        private void SaveToPremissinBackingField(object sender, NotifyCollectionChangedEventArgs e)
        {
            var premissions = sender as ObservableCollection<RolePremission>;
            if (premissions == null) throw new InvalidOperationException("Cant Observe Entitiy 
            AllowedPremissions For DataPresistence");
            this.AllowedRolesPermissions = premissions;
     
`

when i use filter it throws exception
` var roles = IdentityManager.GetCurrentIdentityRoles();
            modelBuilder.Filter("RestrictItemsBaseOnAccses",(IAccessRestrictedItem x) => x.AccessType == AccessType.Public ||
                                                                    x.AllowedRolesPermissions.Any(
                                                                        rp =>
                                                                            rp.AccessPremission == AccessPremission.See &&
                                                                            roles.Contains(rp.RoleName)));`

ex details:

> Property AllowedRolesPermissions not found in Entity Type IAccessRestrictedItem

**Comment by jcachat** [comment]
You can't access unmapped properties in the filter.  The only accessible properties are the ones that EF will be mapping to database columns.  When processing the filter, we do not have instances of the actual C# entity class - only metadata of the conceptual model.
