### ISSUE TITLE
Oracle version check

### ISSUE THREAD

**Issue by lemoinet** [jcachat/EntityFramework.DynamicFilters#118]
Since version 2.8.1 you check for the version of oracle through `OracleVersion` in [src/EntityFramework.DynamicFilters/DynamicFilterExtensions.cs ](src/EntityFramework.DynamicFilters/DynamicFilterExtensions.cs). It's calling the query `select version from v$instance` but most common db-users (non-admin) don't have access to the table/view.
Is there a possibility to change the function to check the version of the database through these queries `select * from v$version;` or `select * from product_component_version;`.

**Comment by jcachat** [comment]
Sorry, I didn't realize that was a restricted table.  I found that recommendation via a google search - I haven't really used Oracle in about 25 years.  I'll get that changed tonight.

**Comment by jcachat** [comment]
Just pushed out a new build (v 2.9.1).  Give that a try and let me know if you have any problems.  It's now using 'product_component_version'.

**Comment by lemoinet** [comment]
Thanks, it's working.
