### ISSUE TITLE
"Contains" doesn't work with SQL CE

### ISSUE THREAD

**Issue by MrStepson** [jcachat/EntityFramework.DynamicFilters#16]
Just for your information - filters with a collection of parameter values doesn't work with SQL CE. The issue is related to SqlCeMultiCommand, which Entity Framework creates for executing requests to SQL CE database. This class overrides CommandText { set; } so it just raises NotSupportedException. Actual command text is located in CommandTexts property, which is an array of strings. Unfortunately, SqlCeMultiCommand is internal, so there is no way to access CommandTexts property without reflection. So I don't know how to fix it...

**Comment by jcachat** [comment]
Unfortunately, there is no way to support Contains on SQL CE.  That provider does not allow changing the CommandText property during sql interception and that is the only way to set the values dynamically.  SQL CE has also been deprecated (as of Feb 2013) so I am not expecting any future changes to the provider.

I have made a change (coming in NuGet package 2.8.0) that will provide a better exception.
