### ISSUE TITLE
Feature request: DisableAllFilters()

### ISSUE THREAD

**Issue by PaulJam** [jcachat/EntityFramework.DynamicFilters#19]
Hi,

It would be nice it there was an extension to disable all filters at once without having to specify every filter explicitly.
I noticed a problem in my project, where the seed method produced duplicate entries because the DbContext.AddOrUpdate() method did an insert instead of an update since the entity was filtered out.
I now disable all filters separately in the seed method, but this has to be adjusted every time a filter gets added or removed.

By the way: The assembly version is still at version 1.3.4 while the nuget package is at 1.3.6

**Comment by jcachat** [comment]
Done.  And correct version # is in NuGet package (now 1.3.7).  I always forget that...

**Comment by PaulJam** [comment]
Awesome!
Thank you.
