### ISSUE TITLE
Any way to handle soft deletes across relationships ?

### ISSUE THREAD

**Issue by leddt** [jcachat/EntityFramework.DynamicFilters#20]
Let's say I have a User entity and a Post entity. A Post belongs to a User.
```
// Simplified model
public class User {
  public int Id {get;set;}
  public string Email {get;set;}

  public bool IsDeleted {get;set;}
  public virtual IList<Post> Posts {get;set;}
}

public class Post {
  public int Id {get;set;}
  public string Title {get;set;}

  [ForeignKey("User_Id")]
  public virtual User {get;set;}
  public int User_Id {get;set;}
}
```

If I mark a User as deleted, can I configure a filter such that Posts by that User will not be returned from queries on the Posts ?

**Comment by jcachat** [comment]
This is actually the same request as issue #11.  I do not have a solution to that yet but it's something I'm trying to figure out right now.  It's something I need myself...

If you create your filter on User.IsDeleted and then .Include(p => p.User) when you query Post, it will filter them out like you want.  But, that's probably not much help unless you always have that .Include().
