### ISSUE TITLE
Unable to DisableFilter() for a single column equality only filter.

### ISSUE THREAD

**Issue by jaymclain** [jcachat/EntityFramework.DynamicFilters#22]
I am receiving a "Filter name {0} not found" error while calling ```DisableFilter()``` on a single column equality-only filter:

Test snippet:

`modelBuilder.Filter("EntityCFilter", (EntityC b) => (b.DeleteTimestamp == null));`

...

`context.DisableFilter("EntityCFilter");`

Yields the error noted above. From what I can tell from the source, the filter is not actually registered correctly for single column equality only filter. So, subsequently it can't be found to be disabled.

I have a change for the Filter() single column scenario, but I'm not sure it's "correct".

**Comment by jcachat** [comment]
Sorry about that.  I just checked in a fix and updated NuGet.  My change is slightly different than yours.  All filters need to be registered in _GlobalParameterValues no matter what so that they can be disabled.  I missed that when I changed how the disabling was done.
