### ISSUE TITLE
DbContext.DisableFilter is not working

### ISSUE THREAD

**Issue by hikalkan** [jcachat/EntityFramework.DynamicFilters#24]
Hi,

This is my code to create and use a DbContext.

    using (var context = new MyDbContext(GetConnectionString("DbConnection")))
    {
        context.DisableFilter("CurrentCustomerFilter");
        //...
    }

DisableFilter method throws exception: **Filter name CurrentCustomerFilter not found.**

I'm defining filter in the MyDbContext.OnModelCreating as like below:

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
       modelBuilder.Filter("CurrentCustomerFilter", (IMustHaveCustomer c) => c.CustomerId, () => AbpSession.TenantId.Value);
    }

When I debug, I see that OnModelCreating is not called when I create first MyDbContext instance. It's called when I try to run a query. So, DynamicFilters library can not find the filter since OnModelCreating is not called yet.

How can I solve this problem?

**Comment by PaulJam** [comment]
Hi,
one possible solution would be to call 
```C#
Database.Initialize(false);
```
in the constructor of the context to make sure OnModelCreating is called before the filter is disabled.

**Comment by jcachat** [comment]
Yeah, you're going to need to Initialize() in the constructor like PaulJam said.  The filters need to be created before I can do anything with them and that's the only way to trigger OnModelCreating().

**Comment by hikalkan** [comment]
Thanks a lot. This solved my problem.
