### ISSUE TITLE
What about query plan cache?

### ISSUE THREAD

**Issue by Korijn** [jcachat/EntityFramework.DynamicFilters#25]
Since this project looks very similar to jbogard's, I'm slightly hesitant to dive in because of the following issue that was registered at his repo: https://github.com/jbogard/EntityFramework.Filters/issues/8 are you aware of this problem and are you working around it?

**Comment by jcachat** [comment]
This project was actually created specifically to fix that issue.  If you search through the comments, you'll see me proposing my solution.  But unfortunately, it didn't fit with his architecture.  I spun off my own project because I needed it for my own use and then shared it here.

**Comment by Korijn** [comment]
I see. Thanks.
