### ISSUE TITLE
StartsWith filter

### ISSUE THREAD

**Issue by easyest** [jcachat/EntityFramework.DynamicFilters#26]
Is there any way to create a filter with `StartsWith` using `DynamicFilters`?

**Comment by jcachat** [comment]
That's not currently supported but I will work on adding that.  Shouldn't be too difficult.

**Comment by easyest** [comment]
At least with simple binding it is implemented just fine with `DbExpressionBuilder.Like` and it is the way Linq translates it to SQL.

**Comment by jcachat** [comment]
Done and Nuget package updated.

**Comment by easyest** [comment]
Thank You a lot. I will test this ASAP.
