### ISSUE TITLE
Wrong SQL generation on Nullable filter values when it's null

### ISSUE THREAD

**Issue by hikalkan** [jcachat/EntityFramework.DynamicFilters#29]
Hi,

I have multi-tenancy filter where it's value can be null (like int?).

When filter's value is set to a non-null value like 1, there is no problem. But when I set filter's value to NULL, I expect to get entities which have a NULL TenantId. But it can not.

I see that generated SQL is wrong:

<pre>exec sp_executesql N'SELECT TOP (1) 
    [Extent1].[Id] AS [Id], 
    [Extent1].[ShouldChangePasswordOnNextLogin] AS [ShouldChangePasswordOnNextLogin], 
    [Extent1].[TenantId] AS [TenantId], 
    [Extent1].[Name] AS [Name], 
    [Extent1].[Surname] AS [Surname]
    FROM [dbo].[AbpUsers] AS [Extent1]
    WHERE 
	(([Extent1].[TenantId] = @DynamicFilterParam_MayHaveTenant_TenantId) OR (@DynamicFilterParam_MayHaveTenant_DynamicFilterIsDisabled IS NOT NULL)) AND
	 (1 = [Extent1].[Id])',	
	N'@DynamicFilterParam_MayHaveTenant_TenantId int,@DynamicFilterParam_MayHaveTenant_DynamicFilterIsDisabled bit',	
	@DynamicFilterParam_MayHaveTenant_TenantId=NULL,
	@DynamicFilterParam_MayHaveTenant_DynamicFilterIsDisabled=NULL</pre>

Look at here:

[Extent1].[TenantId] = @DynamicFilterParam_MayHaveTenant_TenantId

If the value is NULL, it will be like that:

[Extent1].[TenantId] = NULL

and as you know, comparing null should not be like that. Right syntax is:

[Extent1].[TenantId] IS NULL

We should use IS operator instead of = operator. Can you fix it.

Thanks.

**Comment by jcachat** [comment]
Yeah, that's not right and I've reproduced the problem.  In the meantime, I was going to suggest a filter like this:
```
modelBuilder.Filter("EntityEFilter", (EntityE e, int? tenantID) => (!e.TenantID.HasValue && !tenantID.HasValue) || (e.TenantID.HasValue && (e.TenantID == tenantID)), () => null);
```
but that also does not work (throws an exception).

I'll work on these issues.

**Comment by hikalkan** [comment]
Thanks. I'll wait for it since my application is not working now :)

**Comment by jcachat** [comment]
I just pushed a fix for the exception when using the filter I posted above.  If you can pull that down from github, you can set your filter like that and it will do what you need.

I'm still working on supporting the filter as just "e.TenantId == tenantId" (without all the .HasValue checks - which is how the sql will need to be generated).  I'm going to wait on updating NuGet until that's fixed and I can check a couple other things.

**Comment by hikalkan** [comment]
Thanks a lot.

I'm waiting your nuget package push in order to release ABP's new version :)
(https://github.com/aspnetboilerplate/aspnetboilerplate/issues/434)

**Comment by jcachat** [comment]
Should be fixed now and NuGet has been updated.

**Comment by hikalkan** [comment]
Thank you so much. I'll try it.

**Comment by hikalkan** [comment]
It worked, thanks again.
