### ISSUE TITLE
Filter on navigation property

### ISSUE THREAD

**Issue by nextstep79** [jcachat/EntityFramework.DynamicFilters#33]
I am not really sure on whether this is an issue, so bear over with me if this is a behaviour "by design".

I need to set up a filter based on a navigation property -- see below my model:

public class MyEntity
{
       public int ID {get; set;}      
 
       public MyNavigationPropertyOnMyEntity Property1 {get; set;}
}

public class MyNavigationPropertyOnMyEntity 
{
        public int Type {get; set;}
}

I set up a filter like below:

modelBuilder.Filter("MyFilter", (MyEntity) => s.Property1.Type == 1);
 
But I get the following exception:

"Property MyNavigationPropertyOnMyEntity not found in Entity Type MyEntity"

**Comment by jcachat** [comment]
Unfortunately, that's not possible at the moment and is the same issue as #11.  It's something I would like to support but have not found a way to do it yet.

**Comment by nextstep79** [comment]
Do you see any workaround for this, that you can suggest?

**Comment by nextstep79** [comment]
maybe by using a view or a function, in the filter itself? is it possible at all?

**Comment by jcachat** [comment]
A view would probably work for what you're trying to do here.  But I have not tried creating a filter on a view.  If you try it and it doesn't work, create a new issue for it and I'll take a look.

Otherwise, there is no workaround atm.
