### ISSUE TITLE
Supporting Any() in Linq filters

### ISSUE THREAD

**Issue by thisispaulsmith** [jcachat/EntityFramework.DynamicFilters#37]
I'm trying to create a global filter like so

```
modelBuilder.Filter("GroupFilter", (IGroupableEntity e, IEnumerable<int> groups) => e.Groups.Any(g => groups.Contains(g)), new int[0]);
```

Where the interface looks like so...
```
public interface IGroupableEntity
    {
        IEnumerable<int> Groups { get; }
    }
```

The theory being that an entity can be assigned to groups and for a user to view that entity the user must be a member of those groups. 

However the above doesn't work. With the error `Property SGroups not found in Entity Type IGroupableEntity`

Would Any() be supported in a query like this?

**Comment by jcachat** [comment]
There is probably an issue with accessing the collection property.  I'll need to test it to be sure, but I suspect it will be the same issue as #11.  Basically, any property or collection that you need to "Include" in your query is currently off limits in the filtering.  The error message you're getting sounds like that's the main problem here.

"Any" is also not currently supported atm.  But, it's not even be usable if we can't access the child collections.  So the collection issue needs to be figured out first.

I'll check it out in more detail later and let you know.

**Comment by jcachat** [comment]
I tried this out and it is a problem with the Groups collection.  You have that defined as an IEnumberable<int>.  EF can't store collections of primitives like that so this doesn't even get mapped to the db.  To do that, you would need to change "int" to a class that maps as a navigation property.  But, then you will hit the issue with navigation properties not being supported in the filtering.

There is a discussion of this here: http://stackoverflow.com/a/11990836 but the solution of using a ComplexType will probably not work with the filtering.

If you can find a different approach to storing the groups (in a class as a navigation property), you can then create a filter on that class itself.  But you will then be responsible for always "including" the Groups navigation property to get the filter to be applied.  Forgetting to do that would bypass your group check.

**Comment by thisispaulsmith** [comment]
Thanks for the insight. 
The Groups property is already a navigation property however it's generic, hence the need to interface it out. It's like this as a result of Entity Framework inability to map a single class to multiple tables depending on it's location from an aggregate root.

It might be better in this instance just to use a query extension, less flexible but less complex. I'm still looking at other alternatives though.

**Comment by owickedfox** [comment]
I've encountered the same error as @thisispaulsmith too. I have two tables Group (GroupId of Guid) and User (UserId of string) which have a many-to-many relationship. Therefore, there is a table GroupUser. Group, User and GroupUser are all primative types. I would like to filter all the Groups that a certain User belongs to. So I wrote a filter:
<code>
modelBuilder.Filter("GroupsFilter", (Group g, string userId) => g.GroupUsers.Any(gu => gu.UserId == userId), string.Empty);
</code>
So is there any work-around for the filter if Any() hasn't been supported? I have tried to replace Any() by Count() > 0 too and got an error like Unhandled Type of MyDbContext for Constant value in LambdaToDbExpressionVisitor.VisitConstant.

**Comment by jcachat** [comment]
It's not (entirely) an issue with supporting Any().  It's primarily an issue supporting child collections/navigation properties which is issue #11.  The error is being thrown during the parsing of the "g.GroupUsers" part of your filter.  Once I can get that figured out, I'll tackle supporting Any(), Count(), etc.

There really is no good workaround for what you're trying to do.  You could try creating the filter directly on the GroupUsers entity and then "Including" that navigation property in your query.  That will at least filter the GroupUsers collection for you and then you could add a check to see if it's empty.  But that's pretty messy.  I would just not use a Filter on this until I get this issue resolved.

**Comment by chadash** [comment]
Hallo Jcachat!
Maybe the solution of the navigation property (not subcollections) should be to query against a predefined view what includes (joined) the necessary property?
and continuously on the same way,  is it possible to query against a function, and transfer to her a PARAM through the interception methods? if this is possible, we can solve the whole filter-task by that way. and since the filter is defined on a SQL function - it is the most adjustable. (by joins, complex conditions, so on...)
But, these ideas are limited to the option of "casting" this exposed function as a "normal" BbSet.
what is your mind, Jcachat, about these ideas?
The disadvantages are the necessity to build an appropriate pre-filtration SQL functions. while the merits are flexibility and strength of the filters.

**Comment by jcachat** [comment]
I need to think about that a bit more and play around with how functions work in EF.  At this point, I have no idea if I would be able to integrate that into the filters so I don't know if it's even feasible.  It would not be an ideal solution to this particular issue (supporting Any & child collections) but it would open up some interesting possibilities.

**Comment by jcachat** [comment]
Any() and All() are now supported.  Please try this out and let me know how it works.
