### ISSUE TITLE
Should not add any filter if it's disabled

### ISSUE THREAD

**Issue by hikalkan** [jcachat/EntityFramework.DynamicFilters#39]
Hi,

It adds some AND/OR expressions to Where condition of the Query even the filter is disabled. I think it will be better and more performant if it completely remove any conditions related to the filter if it's disabled. Is it possible?

Thanks a lot.

**Comment by jcachat** [comment]
Unfortunately, that's not possible.  EF only gives us 1 chance to intercept the query so we have to inject everything we might possibly need at that time.  Each additional time you execute the same query, it's using a cached query so there is no opportunity to do anything else to it.  All we can do at that point, is intercept the sql and change parameter values.

But, when you disable the filter, the extra conditions should not be causing any extra overhead.  The "is disabled" check is against a parameter value and should be evaluated before sql attempts to look at any database values.

**Comment by hikalkan** [comment]
Thank you very much for your explanation.
