### ISSUE TITLE
Filters for insert/update

### ISSUE THREAD

**Issue by jimmywyatt** [jcachat/EntityFramework.DynamicFilters#43]
I think i might have answered my question when i typed filters into the title, however I basically want to be able to control CRUD operations with separate filters for each operation type, is this something you are doing or it already does, or perhaps have I missed the point?

**Comment by jimmywyatt** [comment]
By the way, either way this is an amazing project and should be included in EF by default.

**Comment by jcachat** [comment]
It only handles queries/selects - not insert/update/delete.  It might be possible to do that but given how EF caches entities and doesn't really provide bulk CUD operations, I'm not sure how well that would fit in.  

Can you describe what you're after?  There are other libraries that provide bulk operations which may do what you need (like these 2: https://github.com/loresoft/EntityFramework.Extended and http://efe.codeplex.com/)

And thanks for the complements - always glad to hear it's helping people.

**Comment by jimmywyatt** [comment]
I would like to be able to write security filters, and then let other developers use the database context with a safety net. I knocked up the following as an example, however it seems like it would be quite expensive

```c#
namespace WindowsFormsApplication1
{
    public class SecurityCheck
    {
        public string Name { get; set; }

        public Type Type { get; set; }

        public Func<IEnumerable<DbEntityEntry>, bool> Rule { get; set; }

        public bool IsEnabled { get; set; }
    }

    public static class SecurityFilterExtensions
    {
        public static void SecurityFilter<T>(this List<SecurityCheck> filters, string name, Func<IEnumerable<DbEntityEntry>, bool> rule) where T : class
        {
            filters.Add(new SecurityCheck()
            {
                Name = name,
                Rule = rule,
                Type = typeof(T),
                IsEnabled = true
            });
        }
    }

    public class DbContextWithFilters : DbContext
    {
        List<SecurityCheck> _securityFilters = new List<SecurityCheck>();

        public virtual void SetupSecurity(List<SecurityCheck> filters)
        {
            
        }
        
        public override int SaveChanges()
        {
            if (!_securityFilters.Any())
            {
                SetupSecurity(_securityFilters);
            }

            var entries = this.ChangeTracker.Entries().ToList();

            foreach (var rule in _securityFilters.Where(x => x.IsEnabled))
            {
                var results = entries.Where(x => x.Entity.GetType() == rule.Type);

                if (!rule.Rule(results))
                {
                    throw new AccessViolationException(string.Format("Operation rejected by security rule '{0}'", rule.Name));
                }
            }

            return base.SaveChanges();
        }
    }

    public class Database : DbContextWithFilters
    {
        public Database()
        {

        }

        public override void SetupSecurity(List<SecurityCheck> filters)
        {
            filters.SecurityFilter<Table1>("Rule1", (entries) =>
            {
                var records = entries.Where(x => x.State == EntityState.Added).Select(x => x.Entity).Cast<Table1>();

                if (records.Any(x => !HasDepartmentAccess(GetCurrentUser(), x.DepartmentNo)))
                    return false;

                return true;
            });

            filters.SecurityFilter<Table2>("Rule2", (entries) =>
            {
                if (entries.Where(x => x.State == EntityState.Modified).Any())
                {
                    return IsAdmin(GetCurrentUser());
                }

                return true;
            });
        }

        public int GetCurrentUser()
        {
            return 1;
        }

        public bool HasDepartmentAccess(int userNo, int departmentNo)
        {
            return (userNo == 1 && departmentNo == 1);                
        }

        public bool IsAdmin(int userNo)
        {
            return userNo == 1;
        }

        public DbSet<Table1> Table1 { get; set; }
        public DbSet<Table2> Table2 { get; set; }
    }
}
```

Just being able to add rules like this would be useful, i think

```c#
             filters.SecurityFilter<Table1>("Rule1", (entries) =>
            {
                var records = entries.Where(x => x.State == EntityState.Added).Select(x => x.Entity).Cast<Table1>();

                if (records.Any(x => !HasDepartmentAccess(GetCurrentUser(), x.DepartmentNo)))
                    return false;

                return true;
            });
```

**Comment by jcachat** [comment]
I think what you're doing there is best done inside the DbContext.SaveChanges as you've shown in your code example.  I actually do several different things like that and tested the performance pretty thoroughly.  I found the performance impact to be negligible/acceptable - it's surprising fast to get entries from the ChangeTracker.

What I'm doing in this project is hooking into the EF query generator.  You can see this in DynamicFilterInterceptor.  The point of doing that is to alter queries that are compiled by EF.  This is never even given an actual entity so it wouldn't even be possible to perform actions like this based on entity values.  That's what DbContext.SaveChanges() is for.

**Comment by jimmywyatt** [comment]
Thanks for you answer, your input, your time. Using both of these will give me what i want and its good to know that performance wise it should be fine.
