### ISSUE TITLE
Postgre support

### ISSUE THREAD

**Issue by klimaxx** [jcachat/EntityFramework.DynamicFilters#44]
Hi

Is there any chance to support postgre db?

**Comment by jcachat** [comment]
I would think it would/will be possible to support but I have not tried it myself.  Have you already tried and gotten errors?

**Comment by klimaxx** [comment]
Hi

I have tried to target your example to postgre 9.3 and this error has been thrown

 {"Parameter DynamicFilterParam_2 must be set"} 
at line 
var list = context1.EntityASet.Include(a => a.Nav1).Include(a => a.Nav2).Include(a => a.Nav3).ToList();

The query is

SELECT "Var_1"."Id", "Var_1"."IsDeleted", "Var_2"."Id" AS "Id1", "Var_2"."IsDeleted" AS "IsDeleted1", "Var_3"."Id" AS "Id2", "Var_3"."IsDeleted" AS "IsDeleted2", "Var_4"."Id" AS "Id3", "Var_4"."IsDeleted" AS "IsDeleted3", "Var_4"."Nav1_Id", "Var_4"."Nav2_Id", "Var_4"."Nav3_Id" 
FROM (SELECT "Var_1"."Nav1_Id", "Var_1"."Nav2_Id", "Var_1"."Nav3_Id", "Var_1"."Id", "Var_1"."IsDeleted" FROM "dbo"."EntityAs" AS "Var_1" 
WHERE "Var_1"."IsDeleted" = @DynamicFilterParam_1 OR @DynamicFilterParam_2 IS NOT NULL) AS "Var_1" LEFT OUTER JOIN (SELECT "Var_2"."Id", "Var_2"."IsDeleted" 
FROM "dbo"."EntityBs" AS "Var_2" 
WHERE "Var_2"."IsDeleted" = @DynamicFilterParam_1 OR @DynamicFilterParam_2 IS NOT NULL) AS "Var_2" 
ON "Var_1"."Nav1_Id" = "Var_2"."Id" 
LEFT OUTER JOIN (SELECT "Var_3"."Id", "Var_3"."IsDeleted" 
FROM "dbo"."EntityBs" AS "Var_3" 
WHERE "Var_3"."IsDeleted" = @DynamicFilterParam_1 OR @DynamicFilterParam_2 IS NOT NULL) AS "Var_3" ON "Var_1"."Nav2_Id" = "Var_3"."Id" 
LEFT OUTER JOIN (SELECT "Var_4"."Id", "Var_4"."IsDeleted", "Var_4"."Nav1_Id", "Var_4"."Nav2_Id", "Var_4"."Nav3_Id" FROM "dbo"."EntityAs" AS "Var_4" 
WHERE "Var_4"."IsDeleted" = @DynamicFilterParam_1 OR @DynamicFilterParam_2 IS NOT NULL) AS "Var_4" ON "Var_1"."Nav3_Id" = "Var_4"."Id"

**Comment by klimaxx** [comment]
Hi

If you want to try it on your own 

1. prepare databases on the server and activate uuid module executing CREATE EXTENSION "uuid-ossp"; command.
2. nuget npgsql and EntityFramework6.Npgsql
3. modify app config

<entityFramework>
    <defaultConnectionFactory type="Npgsql.NpgsqlFactory, Npgsql" />    
    <providers>      
      <provider invariantName="Npgsql" type="Npgsql.NpgsqlServices, EntityFramework6.Npgsql" />
    </providers>
  </entityFramework>
  <connectionStrings>    
    <add name="ExampleContext" connectionString="Server=localhost;port=5432;Database=DynamicFiltersSample1;User Id=postgres;Password=password;" providerName="Npgsql" />
    <add name="SecondContext" connectionString="Server=localhost;port=5432;Database=DynamicFiltersSample2;User Id=postgres;Password=password;" providerName="Npgsql" />
  </connectionStrings>
  <system.data>
    <DbProviderFactories>      
      <add name="Npgsql Data Provider"
          invariant="Npgsql"
          description="Data Provider for PostgreSQL"
          type="Npgsql.NpgsqlFactory, Npgsql" />
    </DbProviderFactories>
  </system.data>

**Comment by jcachat** [comment]
Ok, I'll try to find some time to check this out.  I think your app.config code got mangled in your last post.  Can you edit that to fix?  I have not used postgre before so that will be helpful.

**Comment by klimaxx** [comment]
Hi

I have modified DynamicFilterExtensions.SetSqlParameters

//  If not found, leave as the default that EF assigned (which will be a DBNull)
                if (value == null)
                    continue;

This seems to not work correctly with postgre. Forcing DBNull have made the example work.

**Comment by jcachat** [comment]
Well, that seems like it's too easy.  :)  I'll run that through the unit tests tonight to be sure it works with all of the other DBs.  If it's good, I'll push out a fix and new NuGet package.  

Have you also been able to successfully run all of the unit tests against Postgre?  I have not had time to install Postgre to try it myself.

Thanks!

**Comment by klimaxx** [comment]
All the tests have passed except Contains_DynamicDateTimeOffsetList.

This one has failed with 
The 'DateValue' property on 'EntityK' could not be set to a 'System.DateTime' value. You must set this property to a non-null value of type 'System.DateTimeOffset'. 

   at System.Data.Entity.Core.Common.Internal.Materialization.Shaper.ErrorHandlingValueReader`1.GetValue(DbDataReader reader, Int32 ordinal)
   at System.Data.Entity.Core.Common.Internal.Materialization.Shaper.GetPropertyValueWithErrorHandling[TProperty](Int32 ordinal, String propertyName, String typeName)
   at lambda_method(Closure , Shaper )
   at System.Data.Entity.Core.Common.Internal.Materialization.Shaper.HandleEntityAppendOnly[TEntity](Func`2 constructEntityDelegate, EntityKey entityKey, EntitySet entitySet)
   at lambda_method(Closure , Shaper )
   at System.Data.Entity.Core.Common.Internal.Materialization.Coordinator`1.ReadNextElement(Shaper shaper)
   at System.Data.Entity.Core.Common.Internal.Materialization.Shaper`1.SimpleEnumerator.MoveNext()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at DynamicFiltersTests.ContainsTests.Contains_DynamicDateTimeOffsetList() in c:\Projects\Sandbox\EntityFramework.DynamicFilters\EntityFramework.DynamicFilters\src\DynamicFiltersTests\ContainsTests.cs:line 129

**Comment by jcachat** [comment]
I checked in that change and made a new NuGet package.  I still need to install PostgreSQL so I can check out that failing unit test but hopefully everything else works good for you.

**Comment by jcachat** [comment]
I installed PostgreSQL.  All unit tests pass.  Not sure why Contains_DynamicDateTimeOffsetList was failing before.  Closing this issue but if there is still a problem let me know.
