### ISSUE TITLE
NullReferenceException on querying for null dates

### ISSUE THREAD

**Issue by Jogai** [jcachat/EntityFramework.DynamicFilters#47]
Configured like this:
```C#
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Filter("IsSubscribed", (Subscription subscription) => (subscription.End == null));
        }

        public static ApplicationDbContext Create()
        {
            ApplicationDbContext ctx = new ApplicationDbContext();
            ctx.DisableAllFilters();
            return ctx;
        }
```
Using like this:
```C#
    public class User
    {
        public User(ApplicationDbContext db)
        {
            _db = db;
        }
        public async Task<Contact> GetUser(int id)
        {
            _db.EnableFilter("IsSubscribed");
            return await _db.Contacts
                .Where(c => c.Id == id)
                .Include(c => c.User.Subscriptions)
                .SingleAsync();
        }
    }
```
Gets me this [View fiddle, click 'result'](https://jsfiddle.net/fqngrk3o/embedded/#Result):
 
<table id="t1" style="border-bottom: 2px dashed"><tbody><tr><td class="typeheader" colspan="2">NullReferenceException</td></tr><tr id="sum2"><td colspan="2" class="summary">Object reference not set to an instance of an object.</td></tr><tr><th class="member" title="System.String">Message</th><td>Object reference not set to an instance of an object.</td></tr><tr><th class="member" title="System.Collections.IDictionary">Data</th><td><table id="t3"><tbody><tr><td class="typeheader" colspan="1">(0 items)</td></tr></tbody></table></td></tr><tr><th class="member" title="System.Exception">InnerException</th><td>_null_</td></tr><tr><th class="member" title="System.Reflection.MethodBase">TargetSite</th><td><table id="t4" style="border-bottom: 2px dashed"><tbody><tr><td class="typeheader" colspan="2">RuntimeMethodInfo</td></tr><tr id="sum5"><td colspan="2" class="summary">LambdaToDbExpressionVisitor.VisitMember (MemberExpression node)</td></tr><tr><th class="member" title="System.String">Name</th><td>VisitMember</td></tr><tr><th class="member" title="System.Type">DeclaringType</th><td><div id="c6">typeof(LambdaToDbExpressionVisitor)</div></td></tr><tr><th class="member" title="System.Type">ReflectedType</th><td><div id="c7">typeof(LambdaToDbExpressionVisitor)</div></td></tr><tr><th class="member" title="IEnumerable<System.Reflection.CustomAttributeData>">CustomAttributes</th><td><table id="t8"><tbody><tr><td class="typeheader" colspan="1">(0 items)</td></tr></tbody></table></td></tr><tr><th class="member" title="System.Int32">MetadataToken</th><td>100663385</td></tr><tr><th class="member" title="System.Reflection.Module">Module</th><td><div id="c9">Module</div></td></tr><tr><th class="member" title="System.Reflection.MethodImplAttributes">MethodImplementationFlags</th><td>IL</td></tr><tr><th class="member" title="System.RuntimeMethodHandle">MethodHandle</th><td><table id="t10" style="border-bottom: 2px dashed"><tbody><tr><td class="typeheader" colspan="2">RuntimeMethodHandle</td></tr><tr id="sum11"><td colspan="2" class="summary">System.RuntimeMethodHandle</td></tr><tr><th class="member" title="System.IntPtr">Value</th><td><table id="t12"><tbody><tr><td class="typeheader" colspan="2">IntPtr</td></tr><tr id="sum13"><td colspan="2" class="summary">10996888</td></tr></tbody></table></td></tr></tbody></table></td></tr><tr><th class="member" title="System.Reflection.MethodAttributes">Attributes</th><td>PrivateScope, Family, Virtual, HideBySig</td></tr><tr><th class="member" title="System.Reflection.CallingConventions">CallingConvention</th><td>Standard, HasThis</td></tr><tr><th class="member" title="System.Boolean">IsGenericMethodDefinition</th><td>False</td></tr><tr><th class="member" title="System.Boolean">ContainsGenericParameters</th><td>False</td></tr><tr><th class="member" title="System.Boolean">IsGenericMethod</th><td>False</td></tr><tr><th class="member" title="System.Boolean">IsSecurityCritical</th><td>True</td></tr><tr><th class="member" title="System.Boolean">IsSecuritySafeCritical</th><td>True</td></tr><tr><th class="member" title="System.Boolean">IsSecurityTransparent</th><td>False</td></tr><tr><th class="member" title="System.Boolean">IsPublic</th><td>False</td></tr><tr><th class="member" title="System.Boolean">IsPrivate</th><td>False</td></tr><tr><th class="member" title="System.Boolean">IsFamily</th><td>True</td></tr><tr><th class="member" title="System.Boolean">IsAssembly</th><td>False</td></tr><tr><th class="member" title="System.Boolean">IsFamilyAndAssembly</th><td>False</td></tr><tr><th class="member" title="System.Boolean">IsFamilyOrAssembly</th><td>False</td></tr><tr><th class="member" title="System.Boolean">IsStatic</th><td>False</td></tr><tr><th class="member" title="System.Boolean">IsFinal</th><td>False</td></tr><tr><th class="member" title="System.Boolean">IsVirtual</th><td>True</td></tr><tr><th class="member" title="System.Boolean">IsHideBySig</th><td>True</td></tr><tr><th class="member" title="System.Boolean">IsAbstract</th><td>False</td></tr><tr><th class="member" title="System.Boolean">IsSpecialName</th><td>False</td></tr><tr><th class="member" title="System.Boolean">IsConstructor</th><td>False</td></tr><tr><th class="member" title="System.Reflection.MemberTypes">MemberType</th><td>Method</td></tr><tr><th class="member" title="System.Type">ReturnType</th><td><div id="c14">typeof(Expression)</div></td></tr><tr><th class="member" title="System.Reflection.ParameterInfo">ReturnParameter</th><td><table id="t15" style="border-bottom: 2px dashed"><tbody><tr><td class="typeheader" colspan="2">RuntimeParameterInfo</td></tr><tr id="sum16"><td colspan="2" class="summary">System.Linq.Expressions.Expression </td></tr><tr><th class="member" title="System.Type">ParameterType</th><td><div id="c17">typeof(Expression)</div></td></tr><tr><th class="member" title="System.String">Name</th><td>_null_</td></tr><tr><th class="member" title="System.Boolean">HasDefaultValue</th><td>True</td></tr><tr><th class="member" title="System.Object">DefaultValue</th><td>_null_</td></tr><tr><th class="member" title="System.Object">RawDefaultValue</th><td>_null_</td></tr><tr><th class="member" title="System.Int32">Position</th><td>-1</td></tr><tr><th class="member" title="System.Reflection.ParameterAttributes">Attributes</th><td>None</td></tr><tr><th class="member" title="System.Reflection.MemberInfo">Member</th><td><table id="t18" class="limit" title="Cyclic reference"><tbody><tr><td class="typeheader" colspan="2">RuntimeMethodInfo</td></tr><tr id="sum19"><td colspan="2" class="summary">LambdaToDbExpressionVisitor.VisitMember (MemberExpression node)</td></tr></tbody></table></td></tr><tr><th class="member" title="System.Boolean">IsIn</th><td>False</td></tr><tr><th class="member" title="System.Boolean">IsOut</th><td>False</td></tr><tr><th class="member" title="System.Boolean">IsLcid</th><td>False</td></tr><tr><th class="member" title="System.Boolean">IsRetval</th><td>False</td></tr><tr><th class="member" title="System.Boolean">IsOptional</th><td>False</td></tr><tr><th class="member" title="System.Int32">MetadataToken</th><td>134217728</td></tr><tr><th class="member" title="IEnumerable<System.Reflection.CustomAttributeData>">CustomAttributes</th><td><table id="t20"><tbody><tr><td class="typeheader" colspan="1">(0 items)</td></tr></tbody></table></td></tr></tbody></table></td></tr><tr><th class="member" title="System.Reflection.ICustomAttributeProvider">ReturnTypeCustomAttributes</th><td><table id="t21" style="border-bottom: 2px dashed"><tbody><tr><td class="typeheader" colspan="2">RuntimeParameterInfo</td></tr><tr id="sum22"><td colspan="2" class="summary">System.Linq.Expressions.Expression </td></tr><tr><th class="member" title="System.Type">ParameterType</th><td><div id="c23">typeof(Expression)</div></td></tr><tr><th class="member" title="System.String">Name</th><td>_null_</td></tr><tr><th class="member" title="System.Boolean">HasDefaultValue</th><td>True</td></tr><tr><th class="member" title="System.Object">DefaultValue</th><td>_null_</td></tr><tr><th class="member" title="System.Object">RawDefaultValue</th><td>_null_</td></tr><tr><th class="member" title="System.Int32">Position</th><td>-1</td></tr><tr><th class="member" title="System.Reflection.ParameterAttributes">Attributes</th><td>None</td></tr><tr><th class="member" title="System.Reflection.MemberInfo">Member</th><td><table id="t24" class="limit" title="Cyclic reference"><tbody><tr><td class="typeheader" colspan="2">RuntimeMethodInfo</td></tr><tr id="sum25"><td colspan="2" class="summary">LambdaToDbExpressionVisitor.VisitMember (MemberExpression node)</td></tr></tbody></table></td></tr><tr><th class="member" title="System.Boolean">IsIn</th><td>False</td></tr><tr><th class="member" title="System.Boolean">IsOut</th><td>False</td></tr><tr><th class="member" title="System.Boolean">IsLcid</th><td>False</td></tr><tr><th class="member" title="System.Boolean">IsRetval</th><td>False</td></tr><tr><th class="member" title="System.Boolean">IsOptional</th><td>False</td></tr><tr><th class="member" title="System.Int32">MetadataToken</th><td>134217728</td></tr><tr><th class="member" title="IEnumerable<System.Reflection.CustomAttributeData>">CustomAttributes</th><td><table id="t26"><tbody><tr><td class="typeheader" colspan="1">(0 items)</td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table></td></tr><tr><th class="member" title="System.String">StackTrace</th><td>&nbsp;&nbsp; at EntityFramework.DynamicFilters.LambdaToDbExpressionVisitor.VisitMember(MemberExpression node)
&nbsp;&nbsp; at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
&nbsp;&nbsp; at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
&nbsp;&nbsp; at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
&nbsp;&nbsp; at EntityFramework.DynamicFilters.LambdaToDbExpressionVisitor.VisitUnary(UnaryExpression node)
&nbsp;&nbsp; at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
&nbsp;&nbsp; at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
&nbsp;&nbsp; at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
&nbsp;&nbsp; at EntityFramework.DynamicFilters.LambdaToDbExpressionVisitor.VisitBinary(BinaryExpression node)
&nbsp;&nbsp; at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
&nbsp;&nbsp; at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
&nbsp;&nbsp; at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
&nbsp;&nbsp; at EntityFramework.DynamicFilters.LambdaToDbExpressionVisitor.VisitBinary(BinaryExpression node)
&nbsp;&nbsp; at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
&nbsp;&nbsp; at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
&nbsp;&nbsp; at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
&nbsp;&nbsp; at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
&nbsp;&nbsp; at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
&nbsp;&nbsp; at EntityFramework.DynamicFilters.LambdaToDbExpressionVisitor.Convert(DynamicFilterDefinition filter, DbExpressionBinding binding, ObjectContext objectContext)
&nbsp;&nbsp; at EntityFramework.DynamicFilters.DynamicFilterQueryVisitor.BuildFilterExpressionWithDynamicFilters(String entityName, IEnumerable`1 filterList, DbExpressionBinding binding, DbExpression predicate)
&nbsp;&nbsp; at EntityFramework.DynamicFilters.DynamicFilterQueryVisitor.Visit(DbScanExpression expression)
&nbsp;&nbsp; at System.Data.Entity.Core.Common.CommandTrees.DbScanExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
&nbsp;&nbsp; at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpression(DbExpression expression)
&nbsp;&nbsp; at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpressionBinding(DbExpressionBinding binding)
&nbsp;&nbsp; at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.Visit(DbJoinExpression expression)
&nbsp;&nbsp; at System.Data.Entity.Core.Common.CommandTrees.DbJoinExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
&nbsp;&nbsp; at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpression(DbExpression expression)
&nbsp;&nbsp; at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpressionBinding(DbExpressionBinding binding)
&nbsp;&nbsp; at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.Visit(DbJoinExpression expression)
&nbsp;&nbsp; at System.Data.Entity.Core.Common.CommandTrees.DbJoinExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
&nbsp;&nbsp; at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpression(DbExpression expression)
&nbsp;&nbsp; at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpressionBinding(DbExpressionBinding binding)
&nbsp;&nbsp; at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpressionBindingEnterScope(DbExpressionBinding binding)
&nbsp;&nbsp; at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.Visit(DbFilterExpression expression)
&nbsp;&nbsp; at EntityFramework.DynamicFilters.DynamicFilterQueryVisitor.Visit(DbFilterExpression expression)
&nbsp;&nbsp; at System.Data.Entity.Core.Common.CommandTrees.DbFilterExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
&nbsp;&nbsp; at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpression(DbExpression expression)
&nbsp;&nbsp; at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpressionBinding(DbExpressionBinding binding)
&nbsp;&nbsp; at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpressionBindingEnterScope(DbExpressionBinding binding)
&nbsp;&nbsp; at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.Visit(DbProjectExpression expression)
&nbsp;&nbsp; at System.Data.Entity.Core.Common.CommandTrees.DbProjectExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
&nbsp;&nbsp; at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpression(DbExpression expression)
&nbsp;&nbsp; at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpressionBinding(DbExpressionBinding binding)
&nbsp;&nbsp; at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpressionBindingEnterScope(DbExpressionBinding binding)
&nbsp;&nbsp; at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.Visit(DbSortExpression expression)
&nbsp;&nbsp; at System.Data.Entity.Core.Common.CommandTrees.DbSortExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
&nbsp;&nbsp; at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpression(DbExpression expression)
&nbsp;&nbsp; at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpressionBinding(DbExpressionBinding binding)
&nbsp;&nbsp; at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpressionBindingEnterScope(DbExpressionBinding binding)
&nbsp;&nbsp; at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.Visit(DbProjectExpression expression)
&nbsp;&nbsp; at System.Data.Entity.Core.Common.CommandTrees.DbProjectExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
&nbsp;&nbsp; at EntityFramework.DynamicFilters.DynamicFilterInterceptor.TreeCreated(DbCommandTreeInterceptionContext interceptionContext)
&nbsp;&nbsp; at System.Data.Entity.Infrastructure.Interception.DbCommandTreeDispatcher.<Created>b__0(IDbCommandTreeInterceptor i, DbCommandTreeInterceptionContext c)
&nbsp;&nbsp; at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TInterceptionContext,TResult](TResult result, TInterceptionContext interceptionContext, Action`2 intercept)
&nbsp;&nbsp; at System.Data.Entity.Infrastructure.Interception.DbCommandTreeDispatcher.Created(DbCommandTree commandTree, DbInterceptionContext interceptionContext)
&nbsp;&nbsp; at System.Data.Entity.Core.Common.DbProviderServices.CreateCommandDefinition(DbCommandTree commandTree, DbInterceptionContext interceptionContext)
&nbsp;&nbsp; at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition..ctor(DbProviderFactory storeProviderFactory, DbCommandTree commandTree, DbInterceptionContext interceptionContext, IDbDependencyResolver resolver, BridgeDataReaderFactory bridgeDataReaderFactory, ColumnMapFactory columnMapFactory)
&nbsp;&nbsp; at System.Data.Entity.Core.EntityClient.Internal.EntityProviderServices.CreateDbCommandDefinition(DbProviderManifest providerManifest, DbCommandTree commandTree, DbInterceptionContext interceptionContext)
&nbsp;&nbsp; at System.Data.Entity.Core.Common.DbProviderServices.CreateCommandDefinition(DbCommandTree commandTree, DbInterceptionContext interceptionContext)
&nbsp;&nbsp; at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlanFactory.CreateCommandDefinition(ObjectContext context, DbQueryCommandTree tree)
&nbsp;&nbsp; at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlanFactory.Prepare(ObjectContext context, DbQueryCommandTree tree, Type elementType, MergeOption mergeOption, Boolean streaming, Span span, IEnumerable`1 compiledQueryParameters, AliasGenerator aliasGenerator)
&nbsp;&nbsp; at System.Data.Entity.Core.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
&nbsp;&nbsp; at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__6()
&nbsp;&nbsp; at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
&nbsp;&nbsp; at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
&nbsp;&nbsp; at System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute[TResult](Func`1 operation)
&nbsp;&nbsp; at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
&nbsp;&nbsp; at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
&nbsp;&nbsp; at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
&nbsp;&nbsp; at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
&nbsp;&nbsp; at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)</td></tr><tr><th class="member" title="System.String">HelpLink</th><td>_null_</td></tr><tr><th class="member" title="System.String">Source</th><td>EntityFramework.DynamicFilters</td></tr><tr><th class="member" title="System.Int32">HResult</th><td>-2147467261</td></tr></tbody></table>

**Comment by jcachat** [comment]
Sorry, I haven't responded sooner.  I tried to reproduce the problem but I'm not getting the null exception.  There is a problem with handling the "prop == null" case where it's not being correctly translated to "col is null".  Not sure how I missed that test case (especially since I have a test for "prop != null").  I'll get that fixed as soon as I can.

But, as I said, I'm not getting the null exception and I'm not sure what's causing that.  I'll continue to try some thing to reproduce it.  But in the meantime, there are 2 things I'd like you to try:
1) Move the DisableAllFilters() call to be inside OnModelCreating (after you have created your filters).  
2) Try this syntax on your filter which should work around the "== null" not translating correctly:
```
modelBuilder.Filter("IsSubscribed", (Subscription subscription, DateTime? dt) => (subscription.End == dt), () => null));
```

Let me know if either of these have any effect.

**Comment by jcachat** [comment]
I fixed the issue with the null handling not building the correct sql.  Something changed somewhere since I added handling for that back in Feb...  

Still could not reproduce the null exception you are getting.  But try this and see if it helps.  If not, please post the relevant portions of your models.  And let me know which database & version you are using and Entity Framework version.
