### ISSUE TITLE
bitwise AND in dynamic filter not recognized by Expression Visitor

### ISSUE THREAD

**Issue by themephs** [jcachat/EntityFramework.DynamicFilters#49]
I tried to create a global filter on my context where users can be assigned to any of a number of dynamic "partitions".  Their partition key is compared to an entity's partition key if it is a partitioned item (think like a Customer can be a partition, and a customer's project can be a partition, and users can be constrained within any level of depth within these partitions)

The syntax:

  mb.Filter("FilterPartition",
                (IPartitioned item, int? userPartitionKey) => (!userPartitionKey.HasValue || ((userPartitionKey.Value & item.PartitionKey) == userPartitionKey.Value)),
                      () => CurrentPartitionKey)

When I go to Update-Database i get this error:

"Unhandled NodeType of And in LambdaToDbExpressionVisitor.VisitBinary"

**Comment by jcachat** [comment]
Added support for bitwise operators and pushed an update to NuGet.  Give that a try and let me know if that works for you.

**Comment by themephs** [comment]
Very fast response and works like a charm!  thanks
