### ISSUE TITLE
Loading symbolfiles slow

### ISSUE THREAD

**Issue by nphmuller** [jcachat/EntityFramework.DynamicFilters#52]
I noticed while debugging my project that Visual Studio tries to load (and look for) the symbol files of your this project. This is of course normal and desired behavior. 

However there is one problem: it's much slower than every other project. Sometimes it takes as much as 5 seconds, before Visual Studio gives up and tries to load the symbol files of the next project. This might not seem like much, but in a project with a lot of dependencies, this makes a pretty big impact. Especially if you have to start a new debugging session often.

This piqued my curiosity, so I went on a scavenging hunt and it turns out that this project is trying to load its symbol files from a remote path (\\\\mac\\*something I forgot*). The reason that it takes so much longer than other project is probably because of this. It tries to load from a remote destination, it has to wait for a network timeout and moves on after this.

Is it possible that what I found is true? And if so, is it perhaps possible to change this destination to something else? A local path? I imagine a lot of people have this issue, but not a lot of people really notice it.

**Comment by nphmuller** [comment]
I have found a workaround, but everyone would have to set it up on their own:
-Go to the Options menu of Visual Studio (Tools -> Options).
-Go to Debugging -> Symbols.
-Click on Specify excluded modules.
-Add EntityFramework.Filters.dll

**Comment by jcachat** [comment]
Great find, I had no idea this was happening!  I do most of my work on a Mac using Parallels to run Windows & VS in a VM (I work on mobile apps too so need the Mac for iOS).  My source resides in the host (the Mac) so that's where those UNC paths are coming from.  When I get home tonight, I'll rebuild it on my Windows machine and push out an update.

**Comment by nphmuller** [comment]
Awesome! Thanks a lot!

**Comment by jcachat** [comment]
I pushed an update to NuGet.  Try that and let me know if that fixes the issue.  If so, I'll make sure to do future builds the same way.

**Comment by nphmuller** [comment]
Just tested it and it seems way faster now. Yay! Thanks!
