### ISSUE TITLE
Oracle EF managed driver issue

### ISSUE THREAD

**Issue by risogolo** [jcachat/EntityFramework.DynamicFilters#54]
I'm trying to add some basic filter to the Context class, filter looks like this:
modelBuilder.Filter("filterName", (AdditionalServiceFee asf) => asf.OperatorCode, () => Guid.Parse("ce5648e3-3d21-4336-a878-ac4eac356a3a")); 
I also tried some other various filters...

I'm using Official Oracle ODP.NET, Managed Entity Framework driver 12.1.21, but I have also tried the latest version, which is currently 12.1.2400

When I try to reinitialize DB from the scratch, I'm getting the message:
Additional information: The best overloaded method match for 'Oracle.ManagedDataAccess.EntityFramework.OracleMigrationSqlGenerator.Generate(System.Data.Entity.Migrations.Model.CreateTableOperation)' has some invalid arguments

When I try to Update-database from the migration I'm getting the same message
It seems to me, the behavior is the same for any kind of Filter and it's because the migration can't bee applied for some reason.

**Comment by risogolo** [comment]
I'm going to close this issue, once I deleted all previous migrations and created new initial migration then executed it, since then works as expteced

**Comment by Worthy7** [comment]
Just in case anyone looks here, please check my comment about a bug in the Oracle driver:
https://github.com/zzzprojects/EntityFramework.DynamicFilters/issues/150#issuecomment-485345130
