### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by luke-adams** [jcachat/EntityFramework.DynamicFilters#56]
Sorry, there is no other way I can find to say thank you for this repo: if I've missed an obvious way that I should've sent this message, please forgive me!

You have helped me immensely with the work you have done and I am very, very grateful.

Thank you.

**Comment by jcachat** [comment]
Wow, thank you very much!  I put this out there because there are so many great open source libraries that I use every day and I thought it was good way to give a little back.  It's great to get feedback like this and to hear that it's helping people!
