### ISSUE TITLE
Duplicate filters?

### ISSUE THREAD

**Issue by PrashanthShetty** [jcachat/EntityFramework.DynamicFilters#57]
I have enabled filter for multitenant database, 
modelBuilder.Filter("Tenant", (TenantEntity tenant, Guid tenantId) => tenant.TenantId == tenantId, null);
And I am adding a scoped parameter like
dbContext.SetFilterScopedParameterValue("Tenant", "tenantId", currentUserContext.CurrentTenant.Id);

When i query the database, I see that filter has been added twice.

**WHERE (([Extent1].[TenantId] = @DynamicFilterParam_1) OR (@DynamicFilterParam_2 IS NOT NULL)) AND (([Extent1].[TenantId] = @DynamicFilterParam_1) OR (@DynamicFilterParam_2 IS NOT NULL))**

**Comment by PrashanthShetty** [comment]
My bad, I had added DynamicFilter twice :( 
I had this line of code which was adding duplicate filter.
AddInterceptor(new DynamicFilterInterceptor());

But I am still confused with below query, why  @DynamicFilterParam_2 IS NOT NULL been added?

**WHERE (([Extent1].[StudyId] = @DynamicFilterParam_1) OR (@DynamicFilterParam_2 IS NOT NULL)) **

**Comment by wocar** [comment]
The second parameter is to disable the filter I suppose example:
Select * from Students where (TenantId = [TenantIdParameter] Or
[IsDynamicFilterEnabled] IS NOT NULL)
