### ISSUE TITLE
Filtering .Any() or .All() sub query on navigation property

### ISSUE THREAD

**Issue by Dimaaaa** [jcachat/EntityFramework.DynamicFilters#61]
Hallo, I'm using a SoftDelete filter and have a problem with folowing query
`context.EntityASet.Where(x => x.SubEntities.Any()).ToList();`

EntityASet have 5 items and one SubEntity each. On last two ASet entities the SubEntities set to `IsDeleted = true`

So expected result should be 3 items, but I'm getting all 5 items. The filter seems to work only for result types. 

Here is the full test class

`[TestClass]
    public class SubQueryFilterTests
    {
        [TestMethod]
        public void SubEntity_Any()
        {
            using (var context = new TestContext())
            {
                var q2 = context.EntityASet.Where(x => x.SubEntities.Any()).ToString();
                var list2 = context.EntityASet.Where(x => x.SubEntities.Any()).ToList();
                Assert.IsTrue(list2.Count == 3);
            }
        }

        #region Models

        public class EntityBase : AccountTest.ISoftDelete
        {
            [Key]
            [Required]
            [DatabaseGenerated(DatabaseGeneratedOption.None)]
            public int ID { get; set; }

            public bool IsDeleted { get; set; }

            public virtual List<SubEntityBase> SubEntities { get; set; }
        }
        public class SubEntityBase : AccountTest.ISoftDelete
        {
            [Key]
            [Required]
            [DatabaseGenerated(DatabaseGeneratedOption.None)]
            public int ID { get; set; }

            public bool IsDeleted { get; set; }
        }

        public class EntityA : EntityBase
        {}
        public class SubEntityA : EntityBase
        { }

        #endregion

        #region TestContext

        public class TestContext : TestContextBase<TestContext>, ITestContext
        {
            public DbSet<EntityA> EntityASet { get; set; }

            protected override void OnModelCreating(DbModelBuilder modelBuilder)
            {
                base.OnModelCreating(modelBuilder);

                modelBuilder.Filter("SiftDeleteFilter", (AccountTest.ISoftDelete a) => a.IsDeleted != true);
            }

            public override void Seed()
            {
                for (int i = 1; i <= 5; i++)
                {
                    EntityASet.Add(new EntityA
                                       {
                                           ID = i,
                        SubEntities = new List<SubEntityBase>()
                                          {
                                              new SubEntityBase() { ID = i, IsDeleted = i > 3}
                                          }
                                                       
                                       });
                }

                SaveChanges();
            }
        }

        #endregion
    }`

**Comment by jcachat** [comment]
The problem is that the filters do not support conditions against navigation properties.  See issues #11 and #37.  

Your filter should work fine on both of those entities on their own.  But trying to do "parent.Child.Any()" is what is causing the problem here.

I'll keep this issue open as another example.  I've had partial success in making this work but just don't have it all the way there yet.

**Comment by setoy** [comment]
@jcachat I'm, too, facing the same issue. Do you might want to share what you have achieved until now? I could also take a look at it and maybe create a PR once I got it to work.

**Comment by jcachat** [comment]
It's really not in a state that I could share right now.  It's been an open issue for a very long time and I just haven't had the time to focus on it.  But I'll try to find some time over the next week or 2 to try to make some progress on it.

**Comment by wpycs** [comment]
If user like this
   var query=    from a in DBSetA
                        join b in DBSetB on a.Id equals b.AId into c
                        where c.Any()
                        select a
the sql about table DBSetB also don't have dynamicfilters

**Comment by wpycs** [comment]
My edit may have some problem,I can’t edit last reply.
If DBSetB has a filter condition and condition is variables,the dynamicfilters will work.
like this:
var isActive=true;
var query= from a in DBSetA
join b in DBSetB.Where(d=>d.IsActive=isActive) on a.Id equals b.AId into c
where c.Any()
select a

**Comment by Dimaaaa** [comment]
@jcachat Thank's for reply. I think I found the solution for my problem. I'm not sure about this will fix another issues too.

The solution is to visit predicate too befor creating a new expression
Here is the code

`public override DbExpression Visit(DbFilterExpression expression)
{
	//  If the query contains it's own filter condition (in a .Where() for example), this will be called
	//  before Visit(DbScanExpression).  And it will contain the Predicate specified in that filter.
	//  Need to inject our dynamic filters here and then 'and' the Predicate.  This is necessary so that
	//  the expressions are properly ()'d.
	//  It also allows us to attach our dynamic filter into the same DbExpressionBinding so it will avoid
	//  creating a new sub-query in MS SQL Server.
	var predicate = expression.Predicate;
	var predicateType = expression.Predicate.GetType();
            
	//  Find Visit method for current predicate
	var visitPredicate = this.GetType().GetMethod("Visit", new []{ predicateType });
	if (visitPredicate != null)	
	{	
		//  Visit predicate to use dynemic filter
		predicate = (DbExpression)visitPredicate.Invoke(this, BindingFlags.Default, null, new object[] { expression.Predicate }, CultureInfo.InvariantCulture);
	}

	string entityName = expression.Input.Variable.ResultType.EdmType.Name;
	var containers = _ObjectContext.MetadataWorkspace.GetItems<EntityContainer>(DataSpace.SSpace).First();
	var filterList = FindFiltersForEntitySet(expression.Input.Variable.ResultType.EdmType.MetadataProperties, containers);

	var newFilterExpression = BuildFilterExpressionWithDynamicFilters(entityName, filterList, expression.Input, predicate);
	if (newFilterExpression != null)
	{
		//  If not null, a new DbFilterExpression has been created with our dynamic filters.
		return newFilterExpression;
	}

	return base.Visit(expression);
}`

**Comment by Dimaaaa** [comment]
PS: even more simple and correct just

    var predicate = this.VisitExpression(expression.Predicate);

**Comment by jcachat** [comment]
Thank you!  That works perfectly and does not break any other tests.  

I'm going to do a little more experimentation on it tonight.  After looking at your issue in more detail this morning, I'm not entirely sure it's related to the overall child navigation property issue.  But I want to test out that situation too to see what affect this fix has on that issue.  I've been so focused on fixing this inside the LambdaToDbExpressionVisitor that it never even occurred to me to step back into the QueryVisitor.  Sometimes it just takes another set of (smarter) eyes...

I'll get a new build pushed out tonight at the latest.

**Comment by jcachat** [comment]
Just pushed out the fix and a new build to NuGet.  It turns out this issue has nothing to do with the other 2 issues I mentioned.

Thanks for reporting the issue and especially for providing the fix!

**Comment by jcachat** [comment]
Any() and All() are now supported.  Please try this out and let me know how it works.
