### ISSUE TITLE
Must declare the scalar variable"@DynamicFilterParam_000001"

### ISSUE THREAD

**Issue by magicodes** [jcachat/EntityFramework.DynamicFilters#63]
When I use "EntityFramework.Utilities"，Throw "Must declare the scalar variable @DynamicFilterParam_000001。
This my code:
db.DisableAllFilters(); 
db.BathUpdateBy(db.WeiChat_Users, p => p.Sex == WeChatSexTypes.Man, p => p.Sex, p => WeChatSexTypes.Woman);

public static int BathUpdateBy<TContext, TEntity, TP>(this TContext db, IDbSet<TEntity> dbSet, Expression<Func<TEntity, bool>> whereExp, Expression<Func<TEntity, TP>> propExp, Expression<Func<TEntity, TP>> modifierExp)
           where TContext : DbContext
           where TEntity : class
        {
            var bt = EFBatchOperation.For(db, dbSet);
            return bt.Where(whereExp).Update(propExp, modifierExp);
        }

**Comment by jcachat** [comment]
This is the same issue as #58.  "EntityFramework.Utilities" works the same way as "EntityFramework.Extended".  Neither of those libraries are compatible with DynamicFilters.  Please see that thread for details.

**Comment by magicodes** [comment]
thanks
