### ISSUE TITLE
Filtering on Navigation Properties now available!

### ISSUE THREAD

**Issue by jcachat** [jcachat/EntityFramework.DynamicFilters#65]
Filtering on Navigation Properties is finally here!  (see #11, #37, #61)

I have just pushed up code changes into a new branch called "NavigationProperties" and also pushed out a "pre-release" NuGet package.  To see that NuGet package, you must pick the "Include prerelease" option in the NuGet Package Manager.

For the moment, I am going to leave this in a pre-release state and ask anyone that is able, to please test it and give feedback in this thread.  Once I'm confident it won't affect any existing users, I'll push it out to master and create a "stable" NuGet package.

It required some significant changes to make this work: Instead of intercepting SSpace command trees, we are now intercepting CSpace.  The difference there is that when working with the CSpace metadata, we are essentially working with the .Net models so we have full access to navigation properties.  This allows us to create filters against these properties and when EF does the translation from CSpace -> SSpace, our navigation property filters are automatically included.

This also simplifies several other parts of the query visiting process where we had to put in hacks to make things work.  Primarily, linq conditions in a .Where() clause and Table-per-Type inheritance (issue #32) are handled much cleaner now.

**Comment by jcachat** [comment]
Filtering on single child properties now works as long as the model has the FK properties defined.

So this filter:
```
modelBuilder.Filter("TestFilter", (EntityChild c) => c.ChildValue <= 2);
```
Will work on this model:
```
public class MainEntity
{
    public Guid ChildID { get; set; }
    public EntityChild Child { get; set; }
}
```
But not on this one:
```
public class MainEntity
{
    public EntityChild Child { get; set; }
}
```

The difference being that "ChildID" (the FK) must be defined for the filter to work.  When it is not defined, EF will use naming conventions to add the FK to the data model automatically.  But when it does that, the FK constraint is not available to us when we are applying the filter.  So it is not currently possible to create the necessary join to apply the filter unless the FKs are defined in the model/C# class.

**Comment by jcachat** [comment]
I just released v2 with support for filtering on navigation properties as well as a couple other new features.  See https://github.com/jcachat/EntityFramework.DynamicFilters#changes-in-version-2 for change list.

**Comment by veremenko-jav** [comment]
Thank you very much for an update. But I want to confirm. As I understand one-to-many child properties are not supported. Right?
            
      modelBuilder.Filter("ApplicationsForUser",
                (Application app, int userId) => app.Users.Where(user => user.UserId == userId).Any(),
                () => 100);

**Comment by jcachat** [comment]
Not yet.  I'm going to look into that next.

**Comment by jcachat** [comment]
Another update.  Any() and All() are now supported.  But in that filter above, you'll need to re-write it like this:
```
modelBuilder.Filter("ApplicationsForUser",
            (Application app, int userId) => app.Users.Any(user => user.UserId == userId),
            () => 100);
```

Support for .Where() should be possible but ran out of time tonight.

**Comment by veremenko-jav** [comment]
That is awesome! Thank you!

**Comment by SV-efi** [comment]
@jcachat : Is there any way I can do this in dynamic filter
entity.property does not contain non numeric values.

entity.property type is varchar. But i want to restrict the model to only grab those that contain numeric values. 

the SQL should translate 
NOT LIKE '%[a-ZA-Z]%'

**Comment by jcachat** [comment]
Sorry, no.  There is no equivalent "IsNumeric" method available in linq to translate from.

**Comment by SV-efi** [comment]
Thanks for your reply. I will hack my way thru this.

Srinivasan

**Comment by jcachat** [comment]
I'm not sure if you are trying to filter your SalesOrders to only those that have a Discount with LineNo == 0?  If so, something like this should work.
```
modelBuilder.Filter("filter", (SalesOrder so) => so.Discounts.Any(d => d.LineNo==0));
```

Or if you are trying to filter a child collection of Discounts?  In which case a filter like this will always filter those entities (any time they are involved in any query - individually or inside a child collection):
```
modelBuilder.Filter("filter", (OrderDiscount od) => od.LineNo==0);
```

**Comment by SV-efi** [comment]
The Any Option is not what I am after.

I have Discounts collection of type <OrderDiscount> in both SalesOrder and SalesOrderLine as child

In SalesOrder.Discounts, I want to filter by LineNo == 0.

In SalesOrderLine, I don't want  to filter (because the EF foreign key relationship is set to OrderId, LineNo. )

So to sum up, I want to filter a child collection but only for SalesOrder.Discounts collection not for SalesOrderLine.Discounts.

Thank you for your response.


Thanks,
Srinivasan

**Comment by jcachat** [comment]
There is no way to do that.  The filters are created on a specific entity.  And that is the entity being filtered.  So you can't create a filter on the SalesOrder entity that actually filters the Discount collection.

The best you could do would be to create the filter on the OrderDiscounts as above and then selectively enable/disable it as needed.

But with that said, I now understand why you were asking about .Where().  I'll have to give that some thought.  Maybe if that can be supported it may accomplish what you are after.  I would suggest making a new issue with that specific request and the details you just explained so I don't lose track of it (this is an older closed issue).

**Comment by SV-efi** [comment]
Thank you . Created  #95.


Thanks,
Srinivasan
