### ISSUE TITLE
Delegate Expressions - Context querying (v2)

### ISSUE THREAD

**Issue by veremenko-jav** [jcachat/EntityFramework.DynamicFilters#67]
In v2 you made DbContext available.

`modelBuilder.Filter("Notes_CurrentUser", (Note n) => n.PersonID, (MyContext ctx) => ctx.CurrentPersonID);`

I have complex permission logic and one-to-many child properties are not available. Is the code below unsupported or it is but I'm doing something wrong?

```
modelBuilder.Filter("Filter",
    (User u, List<int> allowed) => allowed.Contains(u.UserId),
    (RegLinkEntities db) => db.UserAccess
        .Where(i => i.UserId == Context.Current.UserId)
        .Select(i => i.AccessedUserId)
        .ToList());
```

**Comment by jcachat** [comment]
Assuming "RegLinkEntities" is a DbContext derived class, it appears that you are executing a db query from inside the filter.  I don't think I would recommend that, but I think it would work.

If it's not, then I would need more information about the problem.

**Comment by veremenko-jav** [comment]
I know it's not good. Now when .Any() is supported I don't need to try this hack. Issue was on doing `Async` query with querying context in `Func<TConext, T>`. It was throwing "A second operation started on this context before a previous asynchronous operation completed."

What would be really helpful instead, is to query context on the filter expression itself to manage connections without foreign keys.

```
modelBuilder.Filter("Value_NoForeignKey", 
    (Note n, MyContext context) => context.Users.Any(u => u.ID == n.PersonID)
);
```

**Comment by jcachat** [comment]
The filter expressions are evaluated when the query parameters are being set.  So executing a query from inside the filter will not work.

Is there a reason you are avoiding making a foreign key?  What you are trying to do there is to enforce the FK relationship on every query operation.  It would be much more efficient to only do that during write operations using a FK since (I assume) you would be doing far less write operations than read.

**Comment by veremenko-jav** [comment]
Laziness? :) I already realized it is not going to work like that and I converted all calculated values to real values within the record.
