### ISSUE TITLE
Wrong SQL generation on nullable values

### ISSUE THREAD

**Issue by hikalkan** [jcachat/EntityFramework.DynamicFilters#69]
Hi,

First of all, I tests with 3 versions:

* Problem with v2.1
* Problem with v2.0
* No problem with v1.4.11.

See the expression below:

````C#
_context.Languages.Any(l => l.TenantId == language.TenantId && l.Name == language.Name)
````

I have a TenantId (multitenancy) filter which is NULLABLE int. language.TenantId value is null in my case. I have also a soft delete filter (which is irrevelant here actually). Generated SQL is that:

````SQL
SELECT 
    CASE WHEN ( EXISTS (SELECT 
        1 AS [C1]
        FROM [dbo].[AbpLanguages] AS [Extent1]
        WHERE ((([Extent1].[TenantId] IS NULL) AND (NULL IS NULL))
               OR (([Extent1].[TenantId] IS NOT NULL) AND ([Extent1].[TenantId] = NULL))
               OR (1 IS NOT NULL))

             AND (([Extent1].[IsDeleted] = 0) OR (1 IS NOT NULL)) 
             
             AND ([Extent1].[TenantId] = NULL)
             
             AND ([Extent1].[Name] = 'en')
             
    )) THEN cast(1 as bit) ELSE cast(0 as bit) END AS [C1]
    FROM  ( SELECT 1 AS X ) AS [SingleRowTable1]
````

I replaced parameters to simplify it. Actual SQL is that:

````SQL
exec sp_executesql N'SELECT 
    CASE WHEN ( EXISTS (SELECT 
        1 AS [C1]
        FROM [dbo].[AbpLanguages] AS [Extent1]
        WHERE ((([Extent1].[TenantId] IS NULL) AND (@DynamicFilterParam_000003 IS NULL)) OR (([Extent1].[TenantId] IS NOT NULL) AND ([Extent1].[TenantId] = @DynamicFilterParam_000003)) OR (@DynamicFilterParam_000004 IS NOT NULL)) AND (([Extent1].[IsDeleted] = @DynamicFilterParam_000001) OR (@DynamicFilterParam_000002 IS NOT NULL)) 
        AND ([Extent1].[TenantId] = @p__linq__0) AND ([Extent1].[Name] = @p__linq__1)
    )) THEN cast(1 as bit) ELSE cast(0 as bit) END AS [C1]
    FROM  ( SELECT 1 AS X ) AS [SingleRowTable1]',N'@DynamicFilterParam_000003 int,@DynamicFilterParam_000004 bit,@DynamicFilterParam_000001 bit,@DynamicFilterParam_000002 bit,@p__linq__0 int,@p__linq__1 nvarchar(4000)',
    
    @DynamicFilterParam_000003=NULL,
    @DynamicFilterParam_000004=1,
    @DynamicFilterParam_000001=0,
    @DynamicFilterParam_000002=1,
    @p__linq__0=NULL,
    @p__linq__1=N'en'
````

``([Extent1].[TenantId] = NULL)`` should be ``([Extent1].[TenantId] IS NULL)`` as you can see (not "=" but "IS"). So, it can not find any row from database as normally.

It's not unique to Any. It's same for FirstOrDefault.

It's propertly working If I change expression like that:

````C#
_context.Languages.Any(l => l.TenantId == null && l.Name == language.Name)
````

I set exlicitly to a null value instead of a variable containing a null value and it worked.

So, it seems there is a bug in v2.0 and later.

**Comment by jcachat** [comment]
The problem was a difference in null handling for the main query conditions (in your case the .Any() clause).  After we process any filters, we create a new DbQueryCommandTree with the results.  Apparently, when translating in CSpace, we need to set a property on that constructor differently in order for the null handling to be done correctly.  That was a difficult one to track down but it turned out to be a very easy fix.

New build being pushed out shortly.  I have a new feature for myself I need to push in too.

**Comment by hikalkan** [comment]
Thank you, looking forward for the next release :)
