### ISSUE TITLE
Accessing dependencies in context

### ISSUE THREAD

**Issue by janhartmann** [jcachat/EntityFramework.DynamicFilters#75]
Thanks for this great library!

Currently trying to restrict my entities to a specific http context user.

Take this context:

```cs
public class MyDbContext : DbContext
{
	private readonly IUserContext _userContext;

	public MyDbContext(IUserContext userContext)
	{
		_userContext = userContext;
	}

	protected override void OnModelCreating(DbModelBuilder modelBuilder)
	{
		modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();

		// Filters
		modelBuilder.Filter(Filters.RestrictEntitiesToCurrentUser, (IUserAwareEntity entity) => entity.UserId, () => _userContext.UserId);
		
		base.OnModelCreating(modelBuilder);
	}
}
```

Apprently I can not have a dependency on the `DbContext` because of this error:

> The target context 'MyDbContext' is not constructible. Add a default constructor or provide an implementation of IDbContextFactory.

I've tried to implement the `IDbContextFactory` but with same result.

How could I access runtime data from these filters? In this example my  `IUserContext` holds the user id from a access token, and I wish to access this one from the filters.

All the best,
Jan

**Comment by jcachat** [comment]
Change your filter to this:
```
modelBuilder.Filter(Filters.RestrictEntitiesToCurrentUser, (IUserAwareEntity entity) => entity.UserId, (MyDbContext ctx) => ctx.UserId);
```

And expose a UserID property from MyDbContext:
```
public int UserId { get { return _ _userContext.UserId; } }
```

Referencing the current DbContext is a new feature in v2.
See: https://github.com/jcachat/EntityFramework.DynamicFilters#changes-in-version-2
and https://github.com/jcachat/EntityFramework.DynamicFilters#parameter-expressions

**Comment by janhartmann** [comment]
Ah, I think I get what you mean!  Thanks a lot! :-)
