### ISSUE TITLE
Unable to use Filters with Independent Association

### ISSUE THREAD

**Issue by honk82** [jcachat/EntityFramework.DynamicFilters#78]
Thank you for a great extension to EF.

However, we have experienced problems with Independent Association mappings and filters.

We get the following exception when executing queries against our DbContext.

> {"FK Constriant not found for association "XXX.Customer_PreferredStore' - must directly specify foreign keys on model to be able to apply this filter"}

We use EF Code First with Fluent Mapping. Our mappings looks like this:

```
class CustomerMap : EntityTypeConfiguration<Customer>
    {
        public CustomerMap()
        {
            HasKey(p => p.Id);
            Property(p => p.IsDeleted).IsRequired();
            Property(p => p.DeleteDate).IsOptional();
            HasOptional(p => p.PreferredStore);
        }
    }
```

```
class StoreMap : EntityTypeConfiguration<Store>
    {
        public StoreMap()
        {
            HasKey(p => p.Id);
            Property(f => f.Name).HasMaxLength(25).IsRequired();
        }
    }
```

And classes...

```
public class Customer : SoftDeletableEntity<int>
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Gender? Gender { get; set; }
        public Store PreferredStore { get; set; }
        public short? YearOfBirth { get; set; }
        public short? MonthOfBirth { get; set; }
        public short? DayOfBirth { get; set; }
    }
```

We don't want to explicitly map a "PreferredStoreId" property to the Customer object to solve the issue, but instead just reference the Store object. Having a PreferredStoreId property on the Customer object and use the following configuration in mapping works;

```
Property(p => p.PreferredStoreId).IsOptional().HasColumnName("PreferredStore_Id");
HasOptional(p => p.PreferredStore).WithMany().HasForeignKey(customer => customer.PreferredStoreId);
```

However we can live with a configuration like this;
`HasOptional(p => p.PreferredStore).WithMany().Map(m => m.MapKey("PreferredStore_Id"));`

where we don't need to clutter our domain model with database specific properties.

Glad for any insights in how we can get around this issue.

**Comment by jcachat** [comment]
Yes, that is a known limitation.  The problem is that we need to use CSpace in order to support building filters on navigation properties.  And in order to make the joins for those filters, we need to known the FK relationships.  Those are not available when using CSpace (EF calculates them in the translation from CSpace -> SSpace) unless they have been specifically defined in the model.

I spent a significant amount of time trying to solve that problem and could not find a solution.  So the only way to make that work is to define the ID properties in your models.

**Comment by honk82** [comment]
Ok, thank you for your fast reply. We will go with the HasForeignKey approach then.
