### ISSUE TITLE
Memory Leak when filtering is enabled

### ISSUE THREAD

**Issue by mcastrobruno** [jcachat/EntityFramework.DynamicFilters#84]
I was testing DynamicFilters for a multi-tenancy application. I'm passing and ID for context and then filtering based on this ID.

I've made a stress test and i've noted that when the filter is turned on the memory usage increases a lot and never is decreased.

Thanks,

Bruno Castro

**Comment by jcachat** [comment]
This library doesn't store anything in memory other than the basic filter configuration which is static, (so stored exactly once) and is a very small amount of data.

You say "when the filter is turned on the memory usage increases".  Have you tried the same stress test without using filters but still executing the exact same queries (by manually adding the conditions)?

**Comment by mcastrobruno** [comment]
Thanks for answering jcachat.
Yes, i've tried the same stress test without the filter and with the same condition, the result is that memory increases but not too much.

Thanks,

Bruno Castro

**Comment by jcachat** [comment]
Is it possible you are not recycling (disposing) your DbContext after each test iteration?  If not, it will continue to cache everything it loads.  And if each test uses a different ID in the query, you will end up loading your database into memory.

**Comment by mcastrobruno** [comment]
You're right, i was not disposing my DbContext.

Thanks for everything jcachat.
