### ISSUE TITLE
How to apply a NOT LIKE '%patern% filter ?

### ISSUE THREAD

**Issue by SV-efi** [jcachat/EntityFramework.DynamicFilters#86]
I have a legacy table which has a non numeric column for primary key /foreign key (Item)
I have another table that the foreign key to this table as numeric.  (OrderItem)
Item table also has some non numeric keys but they will never be found in OrderItem.
I am trying to apply a filter on Item in my model that will translate to this where clause.

WHERE [Item.ItemNo] NOT LIKE '%[a-ZA-Z]%'

How do i achieve that?

**Comment by jcachat** [comment]
Sorry, there is no equivalent "IsNumeric" method available in linq to translate from so this is not possible.

**Comment by jcachat** [comment]
Maybe you could add a computed column to your table and then expose it as a bool property in your model?  Then you could filter on that property.

**Comment by SV-efi** [comment]
You sir, are my hero!

**Comment by jcachat** [comment]
Ha!  Glad to help.  Good luck.
