### ISSUE TITLE
include multi level on error

### ISSUE THREAD

**Issue by ifaron** [jcachat/EntityFramework.DynamicFilters#88]
hi:

An error occurred when I was executing the following statement：

**examRecordRepository.GetQuery().Include(p => p.Exam.Paper)**

occurred  string: {"Unknown column 'Apply1.ExamId' in 'where clause'"}

my code:

    [Table("Exam")]
    public partial class Exam : ModelBase, IMayHaveOrganization
    {
       .....
     }

    [Table("Paper")]
    public partial class Paper : ModelBase, IMayHaveOrganization
    {
      ....
    }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            Database.SetInitializer<OTPDbContext>(null);
            base.OnModelCreating(modelBuilder);
            modelBuilder.Filter(OtpDataFilters.SoftDelete, (ISoftDelete d) => d.IsDeleted, false);
            modelBuilder.Filter(OtpDataFilters.MayHaveOrganization, (IMayHaveOrganization t, string organizationId) => t.OrganizationId == organizationId,  string.Empty);
        }

When I removed the IMayHaveOrganization with Paper, everything was all right.

**Comment by jcachat** [comment]
Please include the relevant parts of the class that are necessary to reproduce the problem.  I need more info than "...."

**Comment by ifaron** [comment]
public interface IMayHaveOrganization
    {
        string OrganizationId
        {
            get;
            set;
        }
    }


 [Table("Exam")]
    public class Exam : IMayHaveOrganization
    {
        [MaxLength(38)]
        public virtual string ID
        {
            get;
            set;
        }  

        public string Name
        {
            get;
            set;
        }

        [Required]
        [MaxLength(38)]
        public string PaperId
        {
            get;
            set;
        }

        [ForeignKey("PaperId")]
        public Paper Paper
        {
            get;
            set;
        }
      
        [Required]
        [MaxLength(38)]
        public string OrganizationId
        {
            get;
            set;
        }




    [Table("Paper")]
    public class Paper : IMayHaveOrganization
    {
        [MaxLength(38)]
        public virtual string ID
        {
            get;
            set;
        }  

        [Required]
        public string Name
        {
            get;
            set;
        }
       
        [Required]
        [MaxLength(38)]
        public string OrganizationId
        {
            get;
            set;
        }       
    }





    [Table("ExamRecord")]
    public class ExamRecord
    {
        [MaxLength(38)]
        public virtual string ID
        {
            get;
            set;
        }  

        [Required]
        [MaxLength(38)]
        public string ExamId
        {
            get;
            set;
        }

        [ForeignKey("ExamId")]
        public Exam Exam
        {
            get;
            set;
        }
    }   





public class DemoDbContext : DbContext
    {
        public DemoDbContext()
            : base()
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            Database.SetInitializer<DemoDbContext>(null);
            base.OnModelCreating(modelBuilder);
            modelBuilder.Filter("OrganizationId", (IMayHaveOrganization t, string organizationId) => t.OrganizationId == organizationId, string.Empty);
        }

        public DbSet<Exam> Exams
        {
            get;
            set;
        }

        public DbSet<ExamRecord> ExamRecords
        {
            get;
            set;
        }


        public DbSet<Paper> Papers
        {
            get;
            set;
        }
    }






    class Program
    {
        static void Main(string[] args)
        {
            using(var dbContext = new DemoDbContext())
            {
                var query = dbContext.ExamRecords.AsQueryable().Include(p => p.Exam.Paper);
                var result = query.ToList();
            }
           
        }
    }

**Comment by jcachat** [comment]
Sorry for the (very) delayed response - I missed responding to this somehow.  I made an update on 1/5/2017 that I believe fixes this issue.  I just copied and pasted your code into a unit test and it seems to work fine - no errors.  Can you please try the latest (version 2.6) if you haven't already and let me know if that resolved the problem for you?

**Comment by ifaron** [comment]
thank you very much！




发自网易邮箱大师
On 05/09/2017 08:54, jcachat wrote:

Sorry for the (very) delayed response - I missed responding to this somehow. I made an update on 1/5/2017 that I believe fixes this issue. I just copied and pasted your code into a unit test and it seems to work fine - no errors. Can you please try the latest (version 2.6) if you haven't already and let me know if that resolved the problem for you?
