### ISSUE TITLE
Selective filtering

### ISSUE THREAD

**Issue by Worthy7** [jcachat/EntityFramework.DynamicFilters#89]
Hello.

I want to have IsDeleted effecitve on all except a few entities.
I want to allow them to be deleted, but just 2 entities I want to show up in the user interface.

Do I 
1) Create a separate interface to use for filtering
2) Disable the filter when using the repository for that entity.

**Comment by jcachat** [comment]
Either of those options will work but, without more information, I cannot make a recommendation as to which is best for your particular use case.

**Comment by Worthy7** [comment]
To show an order has been deleted. Obviously the person handling the order needs to know it has been deleted, so still needs access to it.

**Comment by jcachat** [comment]
I understand why you would want to do that.  But I don't know your code, how you are executing the queries, how changing that interface might affect the rest of your code base, etc...  Either option will accomplish what you are trying to do.  Pick whichever fits in with your architecture the best.

The only recommendation I can make is that if you want to sometimes have those entities filtered and other times not, then you should just disable the filter when needed.
