### ISSUE TITLE
Need support for <= and >= 

### ISSUE THREAD

**Issue by siegeon** [jcachat/EntityFramework.DynamicFilters#9]
Currently I am using jbogard's filters (modified to prevent it from caching the queries. I would love to switch over to your framework, but we need support for <= and >= filters, == is not enough for our use cases. Any chance of this being added?

**Comment by jcachat** [comment]
I just pushed changes to add lambda support.  Contains() is not supported yet in the expression - I'll be working on that next (see #7).

Any testing & feedback would be appreciated.  There will be limits on what can be done in these expressions but if you encounter a filter that does not work or throws some kind of unsupported exception, please let me know and I'll see if I can add support for it.

Filter expressions are configured like this:
`modelBuilder.Filter("BlogEntryFilter", (BlogEntry b, Guid accountID, bool isDeleted) => (b.AccountID == accountID) && (b.IsDeleted == isDeleted), () => CurrentAccountID, () => false);`

where this is defining a filter named "BlogEntryFilter" on the BlogEntry entity with parameters "accountID" and "isDeleted" and the predicate.  The last 2 parameter shown set the values for the 2 filter parameters.  Those can be changed (scoped to the DbContext) via the DbContext.SetFilterScopedParameterValue() method.

The Example app has been updated with some test cases, filter enable/disable, and parameter value changing.

**Comment by siegeon** [comment]
Sweet I will test it out in my implementation.

What are your feelings on setting up a ms test project to test scenerios?

I can make one, the test program is getting a little clunky for expanded
use cases.

I just pushed changes to add lambda support. Contains() is not supported
yet in the expression - I'll be working on that next (see #7
<https://github.com/jcachat/EntityFramework.DynamicFilters/issues/7>).

Any testing & feedback would be appreciated. There will be limits on what
can be done in these expressions but if you encounter a filter that does
not work or throws some kind of unsupported exception, please let me know
and I'll see if I can add support for it.

Filter expressions are configured like this:
modelBuilder.Filter("BlogEntryFilter", (BlogEntry b, Guid accountID, bool
isDeleted) => (b.AccountID == accountID) && (b.IsDeleted == isDeleted), ()
=> CurrentAccountID, () => false);

where this is defining a filter named "BlogEntryFilter" on the BlogEntry
entity with parameters "accountID" and "isDeleted" and the predicate. The
last 2 parameter shown set the values for the 2 filter parameters. Those
can be changed (scoped to the DbContext) via the
DbContext.SetFilterScopedParameterValue() method.

The Example app has been updated with some test cases, filter
enable/disable, and parameter value changing.

—
Reply to this email directly or view it on GitHub
<https://github.com/jcachat/EntityFramework.DynamicFilters/issues/9#issuecomment-68494601>
.

**Comment by jcachat** [comment]
I completely agree on the test project.  I've been meaning to do that but just haven't gotten to it.  If you want to put one together, that would be most appreciated!

**Comment by jcachat** [comment]
I had some time today so I created a unit test project.  Hope that didn't duplicate any work you had done on it.  It was becoming more and more needed...
