### ISSUE TITLE
Filters on inherited classes

### ISSUE THREAD

**Issue by sepptruetsch** [jcachat/EntityFramework.DynamicFilters#93]
Hi

I have a base class of _User_ from which the _Customer_ class is inherited. On this class I would like to enable a SoftDelete just like the example. All classes are in the same Users table, TPH.

But this only works if I add the property and interface on the base _User_ class. Adding/registering this on the _Customer_ class has no effect. The queries to the database (MS SQL) don't get extended with the filter. On the _User_ class I can see the extra filter while profiling. 

```
// works
modelBuilder.Filter("IsDeleted", (ISoftDelete d) => d.DeletedAt, () => null);
// or
modelBuilder.Filter("IsDeleted", (User d) => d.DeletedAt, () => null);

// doesn't work
modelBuilder.Filter("IsDeleted", (Customer d) => d.DeletedAt, () => null);

```

What am I missing? Also, what does InitializeDynamicFilters() do? Is it needed?

By the way, filtering a nullable DateTime also wasn't straight forward. Passing in null as value parameter wouldn't work as I got errors loading entities: 
> {"Value cannot be null.\r\nParameter name: value"}

As delegate it did work tough, for anyone having the same issue.

I'm using the latest NuGet v2.5.0 with EF 6.1.3

Thanks for the great work so far and for any inputs!

**Comment by jcachat** [comment]
My guess is that you are hitting issue #76 (see the last few comments in that thread - not the start).  It's because of the change in v2 to use CSpace instead of SSpace.  But I'll try to put together a test for this to verify.

You do not need to call InitializeDynamicFilters().  It was originally necessary to manually call it but I later changed the other methods to do that automatically.  It was left in for backwards compatibility.

I'll also check on the nullable DateTime.  Not sure why it would work as a delegate and not as a value parameter.

**Comment by jcachat** [comment]
I was able to reproduce both problems (the filter not being applied and the issue with the nullable DateTime).

The filter not applied issue was related to the change to CSpace but not exactly as I was originally thinking.  But the great thing is that in tracking that down, I was also able to finally come up with a solution to #76!

I just pushed out a new build.  Please give this a try and let me know how it works.  It should resolve both issues.

**Comment by sepptruetsch** [comment]
Works perfectly! Tanks for your time and the quick solution!

**Comment by cmp5095** [comment]
The entity models I am working with have a much deeper inheritance hierarchy.  I made the following change so it is recursively looking for an entityset:

        private EntitySet FindEntitySet(EntityContainer containers, EdmType edm)
        {
            var set = containers.EntitySets.FirstOrDefault(e => e.ElementType.Name == edm.Name);

            if (set == null && edm.BaseType != null)
                return FindEntitySet(containers, edm.BaseType);

            return set;
        }

I'd like to see this included if at all possible.
