### ISSUE TITLE
Random NullReferenceException in OnModelCreating

### ISSUE THREAD

**Issue by GitClickOk** [jcachat/EntityFramework.DynamicFilters#94]
First, I want thank you for this amazing component.

Now, I want share my experience about a strange error. I lost an entire day fighting against this error... 

I added this line in the START of the OnModelCreating:

`modelBuilder.Filter("TenantId", (BaseEntity b) => b.TenantId, () => HttpContext.Current.User.Identity.GetTenantId());
`

In my PC everything runs amazing, all entities in the system are correctly filtered by the TenantId. Then I published the software to the test enviroment (AWS EC2), and when I open some Views, works fine, but another Views simply throws NullReferenceException! And this is the only one DynamicFilters code line in all the system... even try-catch dont stop this error.

I though was some kind of SQL metadata error (because when I added DynamicFilters appeared a lot migrations), so I wipe and recreate the entire database and nothing... My dev machine works fine and the published not...

After one entire day researching, I moved the Filter line of code from START of the OnModelCreating (the first line of code) to END, just before of...

`base.OnModelCreating(modelBuilder);`

...and everything works fine now. 

I wonder if DynamicFilters needs some info about FluentAPI that is specified in OnModelCreating method, but if yes, this dont clarify me the mistery of why my development machine works fine but the published enviroment was broken... And if this (put the code in the end) IS a requeriment (isnt obvious for me at least), I think it needed be STATED on the [readme.md](https://github.com/jcachat/EntityFramework.DynamicFilters/blob/master/README.md) page please...

Best Regards

**Comment by jcachat** [comment]
I'm not sure what else you're doing inside OnModelCreating.  But, you should definitely have your filters defined *AFTER* you have fully initialized the model - which includes calling base.OnModelCreating().  The filters are attached to the metadata of the entities in the model (as table attributes.

So define your filters as the last step of OnModelCreating().  I'll update the readme.md page to make that clear - I hadn't thought to mention that.

No idea why it would work on your local machine and not in your test environment.  Were you able to grab the call stack from the null reference exception?

**Comment by GitClickOk** [comment]
I will try reproduce the error again in the test server and I send you

**Comment by jcachat** [comment]
From that bit of stack trace, it looks like a SQL query was executing and the exception occurred when the dynamic filters invoked the delegate to fetch the parameter value.

Based on your filter definition, I would say something in "HttpContext.Current.User.Identity.GetTenantId()" was null or that method was throwing an exception.

Is it possible that something else on your OnModelCreating() was triggered a SQL query?  If so, it could have triggered the dynamic filter when those properties in HttpContext were not initialized.  Moving the filter down in the method would have allowed those queries to execute before the filter was configured.  OnModelCreating is named at the top of the stack trace so it seems like this may be what happened.  Maybe it was even a migration being applied but I think that happens before OnModelCreating() is called.

To be safe, you may want to change the delegate for that parameter to call a method that can do better null checks on those properties.

**Comment by GitClickOk** [comment]
Ok

I will check for nulls and exceptions on "HttpContext.Current.User.Identity.GetTenantId()"

Thanks for your help!
