### ISSUE TITLE
Defautl global filters for all tables, with table Cols Names

### ISSUE THREAD

**Issue by weedkiller** [jcachat/EntityFramework.DynamicFilters#96]
Hi, this is very nice 👍 
For multi-tenant purpose, I have added a `companyId int` field/value to the `aspUsers` table. I also have the `companyId` col in most of the entities/table, and followed your wiki. I want to know if I can set the filter up in OnModelCreating - **and global filter out all tables with column COmpanyId/tenantId**

So, does a a global setting filter exist using a value like tenantId/companyId, i.e. filter all tables with col `companyId` like here, and can it automatically over ride or inject into the local controller dbcontext, can you tell me how to configure and setup/do this, the wiki just shows per table not globally based on a column. However, the typical use case is - the filters are fixed per user-login-session, i.e. he will work on his/one companies records.

1. please tell me how can I set/enable a filter targeted on his companyid. during user login, that will user his `tenantId/companyId` to filterOnly his organizations records when the companyId field is available on the entities, and prevent other visibility.
2. Is the filter per session, and does it dispose automatically when user logs out/? how to implement dispose on time-our or user lock-out as well?
3. In wiki help I only see Query Filter, what about rest CRUD filter like in Dynamic Filters, for updates and deletes on the main table and related tables, can you please include some CRUD filter samples around multitenancy

Thanks
Weedy

**Comment by jcachat** [comment]
Please re-read the wiki.  Everything you are asking about is described there...

Create an interface that defines your CompanyId/tenantId column.  Have all of your entities implement that interface.  Create your filter against the interface.  This is described here with the example of ISoftDelete: https://github.com/jcachat/EntityFramework.DynamicFilters#defining-filters

There are different methods of specifying the value for the filter (in your case the companyId).  Described here: https://github.com/jcachat/EntityFramework.DynamicFilters#defining-filters and https://github.com/jcachat/EntityFramework.DynamicFilters#parameter-expressions.  You will have to figure out what works best for your application.

Filters are defined globally so there is no user session dispose required.

This library does not support CRUD operations.  Only "select" queries.

**Comment by weedkiller** [comment]
Sorry if this sounds like a trivial question.  I looked at the wiki, and I have _not_ implemented interfaces, however, most of my tables have ComapnayId.

Without interfaces, I am hoping I can get past the hurdle of setting up the configuration of a `tenant/companyId/Int` at global scope for all user tables in the user session. I did this but I am struggling on how to get it set/triggered or linked from when the user logs in.

_(this is not ideal, but a sample I'm trying to replace this sort-of functionality  globally, )_
```
public static class EnumerableExtensions
{
    public static T GetOnlyTenantRecords<T>(this IEnumerable<T> source, Func<T, bool> predicate)
    { return source.Where(args => args == User.TenantId).FirstOrDefault(predicate); }
}
```
looking at this help on the DynamicFilters Wiki - it said global scope but seems _specific to one table i.e. `Person `table _ 

- so please share **how do I set this up to filter for `all tables that contain a column for tenantId`**
modelBuilder.Filter("NotesForCompany", (Note n, int orgID) => n.Person.OrganizationID==orgID, (MyContext ctx) => ctx.CurrentOrganizationID);
_______

// Please help with this signature... the wiki did not mention anything on the signature, how to setup the global tenant filter for _all tables/entities_ Is the first part of the signature a filter name, or a variable?
// Tried to pass as a const string, did not work!
modelBuilder.EnableFilter(User.CompanyId, (dbContext ctx) => !ctx.UserIsAdmin);

**Step 1:**
// passing user.CompanyId while user is logging in to setup his tenant specific Dbcontext for all tables
When I try `modelBuilder.EnableFilter(User.CompanyId, (dbContext ctx) => ctx.HowToSEtupFileterAllTables == User.CompanyId);`

A couple of sample code snippets on how to call them for CRUD inside a tenant session would be greatly helpful

**Comment by jcachat** [comment]
The only way to define a single filter that applies to multiple tables is by defining the filter on either a base class or an interface.  There is no other way.

"global scope" means that you define the filter at the application level (in OnModelCreating - which is called once during application start up) and it will apply throughout the application, for all matching queries, and for all user requests.

You are again asking about CRUD.  And again, this library only supports "select" queries so I don't know what else to tell you.

I suggest that you download the project and look at the source code for the test project.  There are numerous examples of how to define filters, pass parameters, etc.
