### ISSUE TITLE
Get by Id issue when use Find method

### ISSUE THREAD

**Issue by procopenco** [jcachat/EntityFramework.DynamicFilters#99]
Hi, 
I have implemented soft-deletable entity
`
interface ISoftDeletableEntity{
   bool Deleted {get;set;}
}
`
I have added filter:

`
 protected override void OnModelCreating(DbModelBuilder modelBuilder)
 {
       //Filter to not retrieve the soft deleted entities
       modelBuilder.Filter("SoftDeletableEntityFilter", (ISoftDeletableEntity d) => d.Deleted, false);
       base.OnModelCreating(modelBuilder);
 }
`

EF allows us to get entity by Id in many ways.
1.  FirstOrDefault  works perfect
var entity = dc.Set<T>().FirstOrDefault(x => x.Id = 1); 

2. Find - doesn't work, is not added the filter  Deleted 
var entity = dc.Set<T>().Find(1); 

I have few entities without regular Id. 
Is it a bug, or I made something wrong ?

**Comment by procopenco** [comment]
I have fixed my issue.  

The method Find doesn't work in integration test because :
1. In test, the entity is inserted, therefore the inserted entity remains in cache 
2. the method Find  get entity from cache if it is exists, it not create a query for it. 

so, just because in test I insert an entity and after that I get it from same context, it is returned from cache. It seems interceptor doesn't work in this moment. 

I have fixed it in a method which do soft delete functionality.

1. the entity has state deleted
2. I set it in updated and Deleted prop set to true, and call savechanges
3. I set the entity state to detached -> in such way it is removed from cache.

**Comment by jcachat** [comment]
These filters are only applied to the database query.  There is no way to apply filters to EF's internal cache.

You should dispose of the DbContext used to create the test data after it has been saved.  Then use a new DbContext for each test you run.  Entities are cached inside the DbContext so this will avoid EF caching from interfering with your test results.
